Sandbox/force-app/main/default/objects/App__c/App__c.object-meta.xml
<CustomObject>
    <description>App alla quale un utente custom sarà collegato</description>
    <label>App</label>
    <nameField>
        <label>Nome App</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Dispositivo__c/Dispositivo__c.object-meta.xml
<CustomObject>
    <description>Dispositivi collegati all&apos;utente per generazione token di sessione</description>
    <label>Dispositivo</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Nome Dispositivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispositivi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Dispositivo__c/fields/Dispositivo__c.field-meta.xml
<CustomField>
    <fullName>Dispositivo__c</fullName>
    <description>Identificativo del dispositivo</description>
    <inlineHelpText>Identificativo del dispositivo</inlineHelpText>
    <label>Dispositivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Dispositivo__c/fields/Firebase_Token__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Token__c</fullName>
    <label>Firebase Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dispositivo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato</description>
    <inlineHelpText>Utente collegato a questo dispositivo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Dispositivi</relationshipLabel>
    <relationshipName>Dispositivi</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/TMI_RCC__c/TMI_RCC__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variabili globali per l&apos;app</description>
    <label>TMI RCC</label>
</CustomObject>

Produzione/force-app/main/default/objects/TMI_RCC__c/fields/Google_Cloud_Functions_URL__c.field-meta.xml
<CustomField>
    <fullName>Google_Cloud_Functions_URL__c</fullName>
    <description>Url google cloud functions</description>
    <inlineHelpText>Url google cloud functions</inlineHelpText>
    <label>Google Cloud Functions URL</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/TMI_RCC__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <description>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</description>
    <inlineHelpText>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</inlineHelpText>
    <label>Secret Key</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomAuthenticationTest.cls
@isTest
public class CustomAuthenticationTest {
	@testSetup
	static void setup() {
		TMI_RCC__c settings = new TMI_RCC__c();

		settings.Secret_Key__c = 'secret';
		settings.Google_Cloud_Functions_URL__c = 'https://us-central1-tmi-rcc-dev.cloudfunctions.net';

		insert settings;

		App__c app = new App__c();

		insert app;

		Utente__c user = new Utente__c();

		user.Nickname__c = 'nickname';
		user.Password__c = 'password';
		user.App__c = app.Id;
		user.Tipologia__c = 'Dealer';

		insert user;

		/*JWT jwt = new JWT();
        
        jwt.setKey(settings.Secret_Key__c);
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Utente__c = user.Id;
        
        insert device;
        
        String token = jwt.encode(new Map<String, Object>{ 'id' => user.Id, 'deviceId' => device.Dispositivo__c }, 60 * 60 * 24 * 30);
        
        device.Firebase_Token__c = token;
        device.Token__c = token;
        
        update device;*/

		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
	}

	static App__c getApp() {
		return [SELECT Id FROM App__c LIMIT 1];
	}

	static Utente__c getUser() {
		return [SELECT Id FROM Utente__c LIMIT 1];
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithoutHeaders() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('nickname', 'password');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithWrongHeaders() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.addHeader('x-bearer-token', 'aaaa');
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', 'aaaa');
		req.addHeader('x-app-id', 'aaaa');

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('nickname', 'password');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithWrongBearer() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('wrong secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', '');

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('nickname', 'password');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithCorrectBearerAndWrongAppId() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		App__c app = new App__c();

		insert app;

		delete app;

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', app.Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('nickname', 'password');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithCorrectParams() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('nickname', 'password');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithBlankUsernameAndPassword() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('', '');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithWrongPassword() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('nickname', 'wrong password');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithBlankPassword() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('nickname', '');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithUsernameAndPasswordWithWrongCredentials() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithNicknameAndPassword('wrong nickname', 'wrong password');
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithWrongToken() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('wrong secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', '');
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithToken();
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithCorrectTokenButMissingDevice() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', jwt.encode(new Map<String, Object>{ 'id' => getUser().Id }, 60 * 5));
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithToken();
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testLoginWithCorrectToken() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		Dispositivo__c device = new Dispositivo__c();

		device.Dispositivo__c = 'deviceId';
		device.Firebase_Token__c = 'firebaseToken';
		device.Token__c = jwt.encode(new Map<String, Object>{ 'id' => getUser().Id }, 60 * 5);
		device.Utente__c = getUser().Id;

		insert device;

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', device.Token__c);
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		ca.authenticateWithToken();
		System.assert(ca.getUser() == null);
	}

	@isTest
	static void testAuthentication() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		Dispositivo__c device = new Dispositivo__c();

		device.Dispositivo__c = 'deviceId';
		device.Firebase_Token__c = 'firebaseToken';
		device.Token__c = jwt.encode(new Map<String, Object>{ 'id' => getUser().Id }, 60 * 5);
		device.Utente__c = getUser().Id;

		insert device;

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', device.Token__c);
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		// System.assert(ca.authenticate());
	}

	@isTest
	static void testAuthenticationWithNotExistingUser() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		Utente__c user = new Utente__c();

		user.Nickname__c = 'nickname2';
		user.Password__c = 'password2';
		user.App__c = getApp().Id;

		insert user;

		delete user;

		Dispositivo__c device = new Dispositivo__c();

		device.Dispositivo__c = 'deviceId';
		device.Firebase_Token__c = 'firebaseToken';
		device.Token__c = jwt.encode(new Map<String, Object>{ 'id' => user.Id }, 60 * 5);
		device.Utente__c = getUser().Id;

		insert device;

		req.addHeader('x-bearer-token', jwt.encode(null, 60));
		req.addHeader('x-device-id', 'deviceId');
		req.addHeader('x-firebase-token', 'firebaseToken');
		req.addHeader('x-auth-token', device.Token__c);
		req.addHeader('x-app-id', getApp().Id);

		CustomAuthentication ca = new CustomAuthentication(req, res);
		System.assert(!ca.authenticate());
	}

	@isTest
	static void testExtras() {
		Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		JWT jwt = new JWT();
		jwt.setKey('secret');

		CustomAuthentication ca = new CustomAuthentication(req, res);

		ca.getDevice();
		ca.getResponse();
		ca.getAuthToken();
		ca.getFirebaseToken();
		ca.getDeviceId();
		ca.getBearerToken();
	}
}