Sandbox/force-app/main/default/objects/App__c/App__c.object-meta.xml
<CustomObject>
    <description>App alla quale un utente custom sarà collegato</description>
    <label>App</label>
    <nameField>
        <label>Nome App</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/App__c/fields/Apple_Store_Url__c.field-meta.xml
<CustomField>
    <fullName>Apple_Store_Url__c</fullName>
    <label>Apple Store Url</label>
    <type>Url</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Contatto_Email__c.field-meta.xml
<CustomField>
    <fullName>Contatto_Email__c</fullName>
    <description>Contatto Email per informazioni app</description>
    <inlineHelpText>Contatto Email per informazioni app</inlineHelpText>
    <label>Contatto Email</label>
    <type>Email</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Contatto_Telefonico__c.field-meta.xml
<CustomField>
    <fullName>Contatto_Telefonico__c</fullName>
    <description>Contatto telefonico di riferimento per l&apos;app</description>
    <inlineHelpText>Contatto telefonico di riferimento per l&apos;app</inlineHelpText>
    <label>Contatto Telefonico</label>
    <type>Phone</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Descrizione_EN__c.field-meta.xml
<CustomField>
    <fullName>Descrizione_EN__c</fullName>
    <label>Descrizione EN</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Descrizione_IT__c.field-meta.xml
<CustomField>
    <fullName>Descrizione_IT__c</fullName>
    <label>Descrizione IT</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Google_Play_Store_Url__c.field-meta.xml
<CustomField>
    <fullName>Google_Play_Store_Url__c</fullName>
    <label>Google Play Store Url</label>
    <type>Url</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Privacy_EN__c.field-meta.xml
<CustomField>
    <fullName>Privacy_EN__c</fullName>
    <label>Privacy EN</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Privacy_IT__c.field-meta.xml
<CustomField>
    <fullName>Privacy_IT__c</fullName>
    <label>Privacy IT</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Versione__c.field-meta.xml
<CustomField>
    <fullName>Versione__c</fullName>
    <label>Versione</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Versione_Android__c.field-meta.xml
<CustomField>
    <fullName>Versione_Android__c</fullName>
    <description>Versione e build android</description>
    <inlineHelpText>Versione e build android</inlineHelpText>
    <label>Versione Android</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/App__c/fields/Versione_IOS__c.field-meta.xml
<CustomField>
    <fullName>Versione_IOS__c</fullName>
    <description>Numero di versione e build ios</description>
    <inlineHelpText>Numero di versione e build ios</inlineHelpText>
    <label>Versione IOS</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/Configurazione_App__c/Configurazione_App__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione dell&apos;app</description>
    <label>Configurazione App</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Nome Configurazione App</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurazioni App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configurazione_App__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Configurazioni App</relationshipLabel>
    <relationshipName>Configurazioni_App</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Booleano__c.field-meta.xml
<CustomField>
    <fullName>Campo_Booleano__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Campo Booleano</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Data__c.field-meta.xml
<CustomField>
    <fullName>Campo_Data__c</fullName>
    <label>Campo Data</label>
    <type>Date</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Data_Ora__c.field-meta.xml
<CustomField>
    <fullName>Campo_Data_Ora__c</fullName>
    <label>Campo Data Ora</label>
    <type>DateTime</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Campo_Numerico__c</fullName>
    <label>Campo Numerico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Testuale__c.field-meta.xml
<CustomField>
    <fullName>Campo_Testuale__c</fullName>
    <label>Campo Testuale</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Chiave__c.field-meta.xml
<CustomField>
    <fullName>Chiave__c</fullName>
    <label>Chiave</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/Configurazione_App__c/fields/Sezione__c.field-meta.xml
<CustomField>
    <fullName>Sezione__c</fullName>
    <label>Sezione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generale</fullName>
            </value>
            <value>
                <fullName>Dealer Map</fullName>
            </value>
            <value>
                <fullName>Dealer Insight</fullName>
            </value>
            <value>
                <fullName>Dealer More Results</fullName>
            </value>
            <value>
                <fullName>Grafici</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Tipologia_Campo__c.field-meta.xml
<CustomField>
    <fullName>Tipologia_Campo__c</fullName>
    <label>Tipologia Campo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Numerico</fullName>
            </value>
            <value>
                <fullName>Testuale</fullName>
            </value>
            <value>
                <fullName>Booleano</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Data Ora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/force-app/main/default/classes/AppInfoResource.cls
@RestResource(urlMapping='/app_info/*')
global class AppInfoResource {
    
    @HttpGet
    global static void doGet(){
        
        String appId = RestContext.request.headers.get('x-app-id'); 
        
        CustomResponse res = new CustomResponse(RestContext.response);
                
        App__c app = null;
        
        try{
            
            app = [SELECT Id, Name, Versione__c, Apple_Store_Url__c, Google_Play_Store_Url__c, Versione_IOS__c, Versione_Android__c, Privacy_IT__c, Privacy_EN__c,
                   Contatto_Telefonico__c, Contatto_Email__c, Descrizione_IT__c, Descrizione_EN__c
                   FROM App__c 
                   WHERE Id = :appId LIMIT 1];
            
            AppInfoData appInfoData = new AppInfoData();
            appInfoData.id = app.Id;
            appInfoData.name = app.Name;
            appInfoData.version = app.Versione__c;
            appInfoData.appleStoreUrl = app.Apple_Store_Url__c;
            appInfoData.googlePlayStoreUrl = app.Google_Play_Store_Url__c;
            appInfoData.iosVersion = app.Versione_IOS__c;
            appInfoData.androidVersion = app.Versione_Android__c;
            appInfoData.privacyIt = app.Privacy_IT__c;
            appInfoData.privacyEn = app.Privacy_EN__c;
            appInfoData.descriptionIt = app.Descrizione_IT__c;
            appInfoData.descriptionEn = app.Descrizione_EN__c;
            appInfoData.phoneContact = app.Contatto_Telefonico__c;
            appInfoData.emailContact = app.Contatto_Email__c;
            appInfoData.configurations = getAppConfigurations(app.Id);
        
            res.setStatusCode(200);
            res.setBody(appInfoData);
            
        }catch(Exception ex){
            
            res.setStatusCode(500);
            res.setBody(new Map<String, Object>{'error' => 'App not found.'});
            
        }
        
        res.send();
        
    }
    
    private static Map<String, Object> getAppConfigurations(Id appId){
        
        Map<String, Object> configurations = new Map<String, Object>();
            
        List<Configurazione_App__c> appConfigurations = [SELECT Id, Name, App__c, Chiave__c, Sezione__c, Tipologia_Campo__c, Campo_Testuale__c, Campo_Numerico__c,
                                                         Campo_Booleano__c, Campo_Data__c, Campo_Data_Ora__c
                                                         FROM Configurazione_App__c
                                                         WHERE App__c = :appId];
        
        for(Configurazione_App__c ca : appConfigurations){
            
            if(!configurations.containsKey(ca.Sezione__c)){
                
                configurations.put(ca.Sezione__c, new Map<String, Object>());
                
            }
            
            Map<String, Object> row = (Map<String, Object>) configurations.get(ca.Sezione__c);
            
            if('Numerico'.equalsIgnoreCase(ca.Tipologia_Campo__c)){
            
                row.put(ca.Chiave__c, ca.Campo_Numerico__c);
                
            }else if('Testuale'.equalsIgnoreCase(ca.Tipologia_Campo__c)){
            
                row.put(ca.Chiave__c, ca.Campo_Testuale__c);
                
            }else if('Booleano'.equalsIgnoreCase(ca.Tipologia_Campo__c)){
            
                row.put(ca.Chiave__c, ca.Campo_Booleano__c);
                
            }else if('Data'.equalsIgnoreCase(ca.Tipologia_Campo__c)){
            
                row.put(ca.Chiave__c, ca.Campo_Data__c);
                
            }else if('Data Ora'.equalsIgnoreCase(ca.Tipologia_Campo__c)){
            
                row.put(ca.Chiave__c, ca.Campo_Data_Ora__c);
                
            }
            
        }
        
        return configurations;
        
    }
    
}