Produzione/force-app/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat utilizzata nei working group</description>
    <label>Chat</label>
    <nameField>
        <displayFormat>CH-{0000000}</displayFormat>
        <label>Nome Chat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>App di riferimento della chat</description>
    <inlineHelpText>App di riferimento della chat</inlineHelpText>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Chat</relationshipLabel>
    <relationshipName>Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Area di riferimento della chat</description>
    <inlineHelpText>Area di riferimento della chat</inlineHelpText>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>After Sales</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Development</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>TFM</fullName>
            </value>
            <value>
                <fullName>TFS</fullName>
            </value>
            <value>
                <fullName>TIM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Descrizione__c.field-meta.xml
<CustomField>
    <fullName>Descrizione__c</fullName>
    <description>Descrizione della chat</description>
    <inlineHelpText>Descrizione della chat</inlineHelpText>
    <label>Descrizione</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome della chat (o nome del gruppo)</description>
    <inlineHelpText>Nome della chat (o nome del gruppo)</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/Chat__c/fields/Proprietario__c.field-meta.xml
<CustomField>
    <fullName>Proprietario__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Chi ha creato la chat</description>
    <inlineHelpText>Chi ha creato la chat</inlineHelpText>
    <label>Proprietario</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Chat</relationshipLabel>
    <relationshipName>Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia della chat, se gruppo o tra 2 persone</description>
    <inlineHelpText>Tipologia della chat, se gruppo o tra 2 persone</inlineHelpText>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>channel</fullName>
                <label>Canale</label>
            </value>
            <value>
                <fullName>direct</fullName>
                <default>true</default>
                <label>Doppia</label>
            </value>
            <value>
                <fullName>group</fullName>
                <label>Gruppo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Dispositivo__c/Dispositivo__c.object-meta.xml
<CustomObject>
    <description>Dispositivi collegati all&apos;utente per generazione token di sessione</description>
    <label>Dispositivo</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Nome Dispositivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispositivi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Dispositivo__c/fields/Dispositivo__c.field-meta.xml
<CustomField>
    <fullName>Dispositivo__c</fullName>
    <description>Identificativo del dispositivo</description>
    <inlineHelpText>Identificativo del dispositivo</inlineHelpText>
    <label>Dispositivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispositivo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato</description>
    <inlineHelpText>Utente collegato a questo dispositivo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Dispositivi</relationshipLabel>
    <relationshipName>Dispositivi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/force-app/main/default/objects/TMI_RCC__c/TMI_RCC__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variabili globali per l&apos;app</description>
    <label>TMI RCC</label>
</CustomObject>

Produzione/force-app/main/default/objects/TMI_RCC__c/fields/Google_Cloud_Functions_URL__c.field-meta.xml
<CustomField>
    <fullName>Google_Cloud_Functions_URL__c</fullName>
    <description>Url google cloud functions</description>
    <inlineHelpText>Url google cloud functions</inlineHelpText>
    <label>Google Cloud Functions URL</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/TMI_RCC__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <description>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</description>
    <inlineHelpText>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</inlineHelpText>
    <label>Secret Key</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Azienda_Permessi_Visualizzazione__c.field-meta.xml
<CustomField>
    <fullName>Azienda_Permessi_Visualizzazione__c</fullName>
    <description>Definisce quali raggruppamenti l&apos;utente manager può visualizzare</description>
    <inlineHelpText>Definisce quali raggruppamenti l&apos;utente manager può visualizzare</inlineHelpText>
    <label>Azienda Permessi Visualizzazione</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Aziende_Permessi_Visualizzazione</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome dell&apos;utente</description>
    <inlineHelpText>Nome dell&apos;utente</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Chat__c/Utente_Chat__c.object-meta.xml
<CustomObject>
    <description>Relazione tra l&apos;utente e la chat utilizzata nel working group</description>
    <label>Utente Chat</label>
    <nameField>
        <displayFormat>UCH-{0000000}</displayFormat>
        <label>Nome Utente Chat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utenti Chat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente_Chat__c/fields/Abilita_Notifiche__c.field-meta.xml
<CustomField>
    <fullName>Abilita_Notifiche__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se selezionato abilita le notifiche via app</description>
    <inlineHelpText>Se selezionato abilita le notifiche via app</inlineHelpText>
    <label>Abilita Notifiche</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Chat__c/fields/Abilita_Storico__c.field-meta.xml
<CustomField>
    <fullName>Abilita_Storico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Abilita la visualizzazione dello storico dei messaggi</description>
    <inlineHelpText>Abilita la visualizzazione dello storico dei messaggi</inlineHelpText>
    <label>Abilita Storico</label>
    <type>Checkbox</type>
</CustomField>

Sandbox/force-app/main/default/objects/Utente_Chat__c/fields/Aggiunto_Da_Utente__c.field-meta.xml
<CustomField>
    <fullName>Aggiunto_Da_Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Definisce da chi è stato aggiunto alla chat l&apos;utente</description>
    <inlineHelpText>Definisce da chi è stato aggiunto alla chat l&apos;utente</inlineHelpText>
    <label>Aggiunto Da Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Chat (Aggiunto Da Utente)</relationshipLabel>
    <relationshipName>Utenti_Chat1</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Utente_Chat__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Chat di riferimento</description>
    <inlineHelpText>Chat di riferimento</inlineHelpText>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Utenti Chat</relationshipLabel>
    <relationshipName>Utenti_Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Utente_Chat__c/fields/Data_Ora_Aggiunta__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Aggiunta__c</fullName>
    <description>Data e ora in cui è stato aggiunto l&apos;utente</description>
    <inlineHelpText>Data e ora in cui è stato aggiunto l&apos;utente</inlineHelpText>
    <label>Data Ora Aggiunta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Utente_Chat__c/fields/Ruolo_Chat__c.field-meta.xml
<CustomField>
    <fullName>Ruolo_Chat__c</fullName>
    <description>Ruolo dell&apos;utente all&apos;interno della chat</description>
    <inlineHelpText>Ruolo dell&apos;utente all&apos;interno della chat</inlineHelpText>
    <label>Ruolo Chat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>admin</fullName>
                <label>Amministratore</label>
            </value>
            <value>
                <fullName>guest</fullName>
                <label>Ospite</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente_Chat__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Utente di riferimento</description>
    <inlineHelpText>Utente di riferimento</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Chat</relationshipLabel>
    <relationshipName>Utenti_Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/ChatResourceTest.cls
@isTest
public class ChatResourceTest {
    
    static String endpoint = '/chats';
    
    @testSetup
    static void setup(){
        
        TMI_RCC__c settings = new TMI_RCC__c();
        
        settings.Secret_Key__c = 'secret';
        settings.Google_Cloud_Functions_URL__c = 'https://us-central1-tmi-rcc-dev.cloudfunctions.net';
        
        insert settings;
        
        App__c app = new App__c();
        
        insert app;
        
        Utente__c user = new Utente__c();
        
        user.Nickname__c = 'nickname';
        user.Password__c = 'password';
        user.App__c = app.Id;
        user.Tipologia__c = 'Dealer';
        user.Azienda_Permessi_Visualizzazione__c = 'TMI';
        
        insert user;
        
        Utente__c user2 = new Utente__c();
        
        user2.Nickname__c = 'nickname2';
        user2.Password__c = 'password2';
        user2.App__c = app.Id;
        user2.Tipologia__c = 'Dealer';
        user.Azienda_Permessi_Visualizzazione__c = 'TMI';
        
        insert user2;
        
        Chat__c chat1 = new Chat__c();
        
        chat1.App__c = app.Id;
        chat1.Area__c = 'Sales';
        chat1.Descrizione__c = 'Desc';
        chat1.Nome__c = 'Chat';
        chat1.Proprietario__c = user.Id;
        
        insert chat1;
        
        Utente_Chat__c userChat1 = new Utente_Chat__c();
        
        userChat1.Chat__c = chat1.Id;
        userChat1.Utente__c = user.Id;
        userChat1.Abilita_Notifiche__c = false;
        userChat1.Abilita_Storico__c = true;
        userChat1.Aggiunto_Da_Utente__c = user.Id;
        userChat1.Data_Ora_Aggiunta__c = System.now();
        userChat1.Ruolo_Chat__c = 'admin';
        
        insert userChat1;
        
        Utente_Chat__c userChat2 = new Utente_Chat__c();
        
        userChat2.Chat__c = chat1.Id;
        userChat2.Utente__c = user2.Id;
        userChat2.Abilita_Notifiche__c = false;
        userChat2.Abilita_Storico__c = true;
        userChat2.Aggiunto_Da_Utente__c = user2.Id;
        userChat2.Data_Ora_Aggiunta__c = System.now();
        userChat2.Ruolo_Chat__c = 'guest';
        
        insert userChat2;
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
    }
    
    static App__c getApp(){
        
        return [SELECT Id FROM App__c LIMIT 1];
        
    }
    
    static Utente__c getUser(){
        
        return [SELECT Id FROM Utente__c LIMIT 1];
        
    }
    
    static Utente__c getUser2(){
        
        return [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
    }
    
    static Chat__c getChat(){
        
        return [SELECT Id FROM Chat__c LIMIT 1];
        
    }
    
    static Gruppo__c getGroup(){
        
        return [SELECT Id FROM Gruppo__c LIMIT 1];
        
    }
    
    static Utente_Chat__c getUserChat(){
        
        return [SELECT Id FROM Utente_Chat__c LIMIT 1];
        
    }
    
    @isTest
    static void testUnauthenticatedGet(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('wrong secret');
        
        req.requestURI = endpoint;
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testUnauthenticatedPost(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('wrong secret');
        
        req.requestURI = endpoint;
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostChats(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        req.requestURI = endpoint;
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
        req.requestBody = Blob.valueOf('{"chat_title":"Gruppo","chat_description":"Descrizione","chat_area":"Sales","chat_image_url":null,"members": ["' + u.Id + '"]}');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostCreateDirectChat(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        req.requestURI = endpoint;
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
        req.requestBody = Blob.valueOf('{"chat_title":null,"chat_description":null,"chat_area":null,"chat_image_url":null,"members": ["' + u.Id + '"],"chat_type":"direct"}');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostUpdateChat(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        
        req.requestURI = endpoint + '/' + chat.Id;
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
        req.requestBody = Blob.valueOf('{"chat_title":"Gruppo2","chat_description":"Descrizione2","chat_area":"Sales","chat_image_url":null}');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostAddMembersToChat(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        Utente__c user = getUser2();
        
        req.requestURI = endpoint + '/' + chat.Id + '/members';
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
        req.requestBody = Blob.valueOf('{"members": [{"userId": "' + user.Id + '", "historyEnabled": true}]}');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostChatToggleAdmin(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        Utente__c user = getUser();
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        //Utente_Chat__c uc = [SELECT Id FROM Utente_Chat__c WHERE Utente__c = :u.Id AND Chat__c = :chat.Id LIMIT 1];
        
        req.requestURI = endpoint + '/' + chat.Id + '/members/' + u.Id + '/toggleAdmin';
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        req.requestBody = Blob.valueOf('{"members": [{"userId": "' + u.Id + '", "historyEnabled": true}]}');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        //System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostWrong(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        req.requestURI = endpoint + 'asdasxa';
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
        req.requestBody = Blob.valueOf('{"chat_title":"Gruppo","chat_description":"Descrizione","chat_area":"Sales","chat_image_url":null,"members": ["' + u.Id + '"]}');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        //System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostChatExit(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        Utente_Chat__c member = getUserChat();
        
        req.requestURI = endpoint + '/' + chat.Id + '/members/' + member.Id + '/exit';
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
        req.requestBody = Blob.valueOf('');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedPostChatToggleNotifications(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        
        req.requestURI = endpoint + '/' + chat.Id + '/notifications';
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Utente__c u = [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname2' LIMIT 1];
        
        req.requestBody = Blob.valueOf('');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doPost();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedGetChats(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        req.requestURI = endpoint;
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedGetWrong(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        req.requestURI = endpoint + '/asdxasd';
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        //System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedGetChatsMembers(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        req.requestURI = endpoint + '/members';
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedGetChatMembers(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        
        req.requestURI = endpoint + '/' + chat.Id + '/members';
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedGetChatMemberNotificationStatus(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        
        req.requestURI = endpoint + '/' + chat.Id + '/notifications';
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testAuthenticatedGetChatMemberInfo(){
        
        Test.setMock(HttpCalloutMock.class, new CloudFunctionsHttpMock());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Chat__c chat = getChat();
        Utente__c user = getUser();
        
        req.requestURI = endpoint + '/' + chat.Id + '/members/' + user.Id;
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        Test.startTest();
        
        ChatResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }

}