Produzione/force-app/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat utilizzata nei working group</description>
    <label>Chat</label>
    <nameField>
        <displayFormat>CH-{0000000}</displayFormat>
        <label>Nome Chat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>App di riferimento della chat</description>
    <inlineHelpText>App di riferimento della chat</inlineHelpText>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Chat</relationshipLabel>
    <relationshipName>Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Area di riferimento della chat</description>
    <inlineHelpText>Area di riferimento della chat</inlineHelpText>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>After Sales</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Development</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>TFM</fullName>
            </value>
            <value>
                <fullName>TFS</fullName>
            </value>
            <value>
                <fullName>TIM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Data_Ora_Chiusura__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Chiusura__c</fullName>
    <description>Data e ora della chiusura. Se impostata non sarà più possibile scrivere all&apos;interno della chat</description>
    <inlineHelpText>Data e ora della chiusura. Se impostata non sarà più possibile scrivere all&apos;interno della chat</inlineHelpText>
    <label>Data Ora Chiusura</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Data_Ora_Eliminazione__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Eliminazione__c</fullName>
    <description>Data e ora dell&apos;eliminazione della chat. Se impostata non è più possibile accedere alla chat</description>
    <inlineHelpText>Data e ora dell&apos;eliminazione della chat. Se impostata non è più possibile accedere alla chat</inlineHelpText>
    <label>Data Ora Eliminazione</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Descrizione__c.field-meta.xml
<CustomField>
    <fullName>Descrizione__c</fullName>
    <description>Descrizione della chat</description>
    <inlineHelpText>Descrizione della chat</inlineHelpText>
    <label>Descrizione</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome della chat (o nome del gruppo)</description>
    <inlineHelpText>Nome della chat (o nome del gruppo)</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/Chat__c/fields/Proprietario__c.field-meta.xml
<CustomField>
    <fullName>Proprietario__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Chi ha creato la chat</description>
    <inlineHelpText>Chi ha creato la chat</inlineHelpText>
    <label>Proprietario</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Chat</relationshipLabel>
    <relationshipName>Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Riferimento_Immagine__c.field-meta.xml
<CustomField>
    <fullName>Riferimento_Immagine__c</fullName>
    <description>Riferimento firebase all&apos;immagine</description>
    <label>Riferimento Immagine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia della chat, se gruppo o tra 2 persone</description>
    <inlineHelpText>Tipologia della chat, se gruppo o tra 2 persone</inlineHelpText>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>channel</fullName>
                <label>Canale</label>
            </value>
            <value>
                <fullName>direct</fullName>
                <default>true</default>
                <label>Doppia</label>
            </value>
            <value>
                <fullName>group</fullName>
                <label>Gruppo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat__c/fields/URL_Immagine__c.field-meta.xml
<CustomField>
    <fullName>URL_Immagine__c</fullName>
    <description>URL dell&apos;immagine della chat</description>
    <inlineHelpText>URL dell&apos;immagine della chat</inlineHelpText>
    <label>URL Immagine</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/Dispositivo__c/Dispositivo__c.object-meta.xml
<CustomObject>
    <description>Dispositivi collegati all&apos;utente per generazione token di sessione</description>
    <label>Dispositivo</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Nome Dispositivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispositivi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Dispositivo__c/fields/Dispositivo__c.field-meta.xml
<CustomField>
    <fullName>Dispositivo__c</fullName>
    <description>Identificativo del dispositivo</description>
    <inlineHelpText>Identificativo del dispositivo</inlineHelpText>
    <label>Dispositivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Dispositivo__c/fields/Firebase_Token__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Token__c</fullName>
    <label>Firebase Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dispositivo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato</description>
    <inlineHelpText>Utente collegato a questo dispositivo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Dispositivi</relationshipLabel>
    <relationshipName>Dispositivi</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/TMI_RCC__c/TMI_RCC__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variabili globali per l&apos;app</description>
    <label>TMI RCC</label>
</CustomObject>

Produzione/force-app/main/default/objects/TMI_RCC__c/fields/Google_Cloud_Functions_URL__c.field-meta.xml
<CustomField>
    <fullName>Google_Cloud_Functions_URL__c</fullName>
    <description>Url google cloud functions</description>
    <inlineHelpText>Url google cloud functions</inlineHelpText>
    <label>Google Cloud Functions URL</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/TMI_RCC__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <description>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</description>
    <inlineHelpText>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</inlineHelpText>
    <label>Secret Key</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Azienda__c.field-meta.xml
<CustomField>
    <fullName>Azienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Azienda</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Cognome__c.field-meta.xml
<CustomField>
    <fullName>Cognome__c</fullName>
    <description>Cognome dell&apos;utente</description>
    <inlineHelpText>Cognome dell&apos;utente</inlineHelpText>
    <label>Cognome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome dell&apos;utente</description>
    <inlineHelpText>Nome dell&apos;utente</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Ragione_Sociale__c.field-meta.xml
<CustomField>
    <fullName>Ragione_Sociale__c</fullName>
    <description>Ragione sociale dell&apos;azienda collegata</description>
    <inlineHelpText>Ragione sociale dell&apos;azienda collegata</inlineHelpText>
    <label>Ragione Sociale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Riferimento_Immagine_Profilo__c.field-meta.xml
<CustomField>
    <fullName>Riferimento_Immagine_Profilo__c</fullName>
    <description>Riferimento firebase all&apos;immagine</description>
    <label>Riferimento Immagine Profilo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Ruolo__c.field-meta.xml
<CustomField>
    <fullName>Ruolo__c</fullName>
    <description>Ruolo del contatto</description>
    <label>Ruolo</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente__c/fields/URL_Foto__c.field-meta.xml
<CustomField>
    <fullName>URL_Foto__c</fullName>
    <description>Url per la foto del profilo utente</description>
    <inlineHelpText>Url per la foto del profilo utente</inlineHelpText>
    <label>URL Foto</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Chat__c/Utente_Chat__c.object-meta.xml
<CustomObject>
    <description>Relazione tra l&apos;utente e la chat utilizzata nel working group</description>
    <label>Utente Chat</label>
    <nameField>
        <displayFormat>UCH-{0000000}</displayFormat>
        <label>Nome Utente Chat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utenti Chat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente_Chat__c/fields/Abilita_Storico__c.field-meta.xml
<CustomField>
    <fullName>Abilita_Storico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Abilita la visualizzazione dello storico dei messaggi</description>
    <inlineHelpText>Abilita la visualizzazione dello storico dei messaggi</inlineHelpText>
    <label>Abilita Storico</label>
    <type>Checkbox</type>
</CustomField>

Sandbox/force-app/main/default/objects/Utente_Chat__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Chat di riferimento</description>
    <inlineHelpText>Chat di riferimento</inlineHelpText>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Utenti Chat</relationshipLabel>
    <relationshipName>Utenti_Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente_Chat__c/fields/Ruolo_Chat__c.field-meta.xml
<CustomField>
    <fullName>Ruolo_Chat__c</fullName>
    <description>Ruolo dell&apos;utente all&apos;interno della chat</description>
    <inlineHelpText>Ruolo dell&apos;utente all&apos;interno della chat</inlineHelpText>
    <label>Ruolo Chat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>admin</fullName>
                <label>Amministratore</label>
            </value>
            <value>
                <fullName>guest</fullName>
                <label>Ospite</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente_Chat__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Utente di riferimento</description>
    <inlineHelpText>Utente di riferimento</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Chat</relationshipLabel>
    <relationshipName>Utenti_Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/QCloudFunctions.cls
public class QCloudFunctions {
    
    private static String cloudFunctionsUrl = TMI_RCC__c.getOrgDefaults().Google_Cloud_Functions_URL__c;
    private static String secretKey = TMI_RCC__c.getOrgDefaults().Secret_Key__c;
    
    @future(callout = true)
    public static void doRequest(String endpoint, String method, String requestBody, Map<String, String> headers){
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(cloudFunctionsUrl + endpoint);
        req.setMethod(method.toUpperCase());
        
        JWT jwt = new JWT();
        jwt.setKey(secretKey);
        
        System.debug(requestBody);
        
        req.setHeader('X-Bearer-Token', jwt.encode(new Map<String, Object>{'endpoint' => endpoint}, 60 * 5));
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        
        req.setBody(requestBody);
        
        Http http = new Http();
        
        HTTPResponse res = http.send(req);
        
        System.debug(res.getBody());
        
    }
    
    public class QFirebaseMessageNotificationPayload{
        
        public String title;
        public String body;
        
        public QFirebaseMessageNotificationPayload(){}
        
    }
    
    public class QFirebaseMessagePayload{
        
        public QFirebaseMessagePayload(){}
        
    }
    
    public class QFirebaseMessageUserPayload{
        
        public String id;
        public String user_id;
        public Boolean history;
        public Long created_at;
        public Long deleted_at;
        public String company_name;
        public String first_name;
        public String last_name;
        public String img;
        public String role;
        public String user_type;
        
        public QFirebaseMessageUserPayload(){}
        
    }
    
    public class QFirebaseMessageChatPayload{
        
        public String id;
        public String app_id;
        public String area;
        public Long closed_at;
        public Long updated_at;
        public Long deleted_at;
        public String description;
        public String title;
        public String owner_id;
        public String chat_type;
        public String image_url;
        public String image_path;
        public List<QFirebaseMessageUserPayload> members = new List<QFirebaseMessageUserPayload>();
        
        public QFirebaseMessageChatPayload(){}       
        
    }
    
    public class QFirebaseMessage{
        
        public String app_id;
        public String chat_id;
        public String chat_role;
        public Long created_at = System.now().getTime() * 1000;
        public Long deleted_at;
        public Long updated_at;
        public String message_category = 'system';
        public String message_type;
        public Boolean notify = false;
        public String user_id;
        public Boolean history = true;
        
        public List<String> user_fcm_tokens = new List<String>();
        
        public QFirebaseMessageNotificationPayload notification_payload = new QFirebaseMessageNotificationPayload();
        public QFirebaseMessagePayload payload = new QFirebaseMessagePayload();
        public QFirebaseMessageUserPayload user_payload = new QFirebaseMessageUserPayload();
        public QFirebaseMessageChatPayload chat_payload = new QFirebaseMessageChatPayload();
        
        public QFirebaseMessage(){}
        
        public void setUserFields(Utente__c user){
            
            if(user != null){
                
            	this.user_id = user.Id;
                
                this.user_payload.company_name = user.Ragione_Sociale__c;
                this.user_payload.first_name = user.Nome__c;
                this.user_payload.img = user.URL_Foto__c;
                this.user_payload.last_name = user.Cognome__c;
                this.user_payload.role = user.Ruolo__c;
                this.user_payload.user_type = user.Tipologia__c;
                
                for(Dispositivo__c d : user.Dispositivi__r){
                    
                    this.user_fcm_tokens.add(d.Firebase_Token__c);
                    
                }
                
            }
            
        }
        
        public void setChatFields(Chat__c chat){            
            
            this.app_id = chat.App__c;
            this.chat_id = chat.Id;
            
            this.chat_payload.id = chat.Id;
            this.chat_payload.app_id = chat.App__c;
            this.chat_payload.area = chat.Area__c;
            this.chat_payload.closed_at = chat.Data_Ora_Chiusura__c != null ? chat.Data_Ora_Chiusura__c.getTime() : null;
            this.chat_payload.updated_at = chat.LastModifiedDate != null ? chat.LastModifiedDate.getTime() : null;
            this.chat_payload.deleted_at = chat.Data_Ora_Eliminazione__c != null ? chat.Data_Ora_Eliminazione__c.getTime() : null;
            this.chat_payload.description = chat.Descrizione__c;
            this.chat_payload.title = chat.Nome__c;
            this.chat_payload.owner_id = chat.Proprietario__c;
            this.chat_payload.chat_type = chat.Tipologia__c;
            this.chat_payload.image_url = chat.URL_Immagine__c;
            this.chat_payload.image_path = chat.Riferimento_Immagine__c;
            
        }
        
        public void setUserChatFields(Utente_Chat__c userChat){    
            
            this.chat_role = userChat.Ruolo_Chat__c;
            
        }
        
        public void setChatMembersFields(List<Utente_Chat__c> members){    
            
            for(Utente_Chat__c member : members){
                
                QFirebaseMessageUserPayload userPayload = new QFirebaseMessageUserPayload();
                
                userPayload.company_name = member.Utente__r.Azienda__c;
                userPayload.first_name = member.Utente__r.Nome__c;
                userPayload.last_name = member.Utente__r.Cognome__c;
                userPayload.img = member.Utente__r.Riferimento_Immagine_Profilo__c;
                userPayload.role = member.Ruolo_Chat__c;
                userPayload.user_type = member.Utente__r.Tipologia__c;
                userPayload.id = member.Id;
                userPayload.user_id = member.Utente__c;
                userPayload.history = member.Abilita_Storico__c;
                userPayload.created_at = member.Data_Ora_Aggiunta__c != null ? member.Data_Ora_Aggiunta__c.getTime() : null;
                userPayload.deleted_at = member.Data_Ora_Rimozione__c != null ? member.Data_Ora_Rimozione__c.getTime() : null;
                
                this.chat_payload.members.add(userPayload);
            }
            
        }
        
    }

}