Produzione/force-app/main/default/objects/Articolo__c/Articolo__c.object-meta.xml
<CustomObject>
    <description>Oggetto per la gestione degli articoli all&apos;interno della app</description>
    <label>Articolo</label>
    <nameField>
        <displayFormat>ART-{00000000}</displayFormat>
        <label>Nome Articolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Articoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Articolo__c/fields/Allegato_1__c.field-meta.xml
<CustomField>
    <fullName>Allegato_1__c</fullName>
    <description>Url o riferimento dell&apos;articolo</description>
    <inlineHelpText>Url o riferimento dell&apos;articolo</inlineHelpText>
    <label>Allegato 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Articolo__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Area per la classificazione dell&apos;articolo</description>
    <inlineHelpText>Area per la classificazione dell&apos;articolo</inlineHelpText>
    <label>Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Permessi_Visualizzazione</valueSetName>
    </valueSet>
</CustomField>

Sandbox/force-app/main/default/objects/Articolo__c/fields/Autore__c.field-meta.xml
<CustomField>
    <fullName>Autore__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Utente autore dell&apos;articolo</description>
    <label>Autore</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Articoli</relationshipLabel>
    <relationshipName>Articoli</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Articolo__c/fields/Contenuto__c.field-meta.xml
<CustomField>
    <fullName>Contenuto__c</fullName>
    <description>Contenuto dell&apos;articolo</description>
    <inlineHelpText>Contenuto dell&apos;articolo</inlineHelpText>
    <label>Contenuto</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Articolo__c/fields/Data_Ora_Pubblicazione__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Pubblicazione__c</fullName>
    <description>Data in cui l&apos;articolo deve essere pubblicato</description>
    <inlineHelpText>Data in cui l&apos;articolo deve essere pubblicato</inlineHelpText>
    <label>Data Ora Pubblicazione</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

Produzione/force-app/main/default/objects/Articolo__c/fields/Immagine_Di_Copertina__c.field-meta.xml
<CustomField>
    <fullName>Immagine_Di_Copertina__c</fullName>
    <description>Immagine di copertina eventuale all&apos;articolo</description>
    <inlineHelpText>Immagine di copertina eventuale all&apos;articolo</inlineHelpText>
    <label>Immagine Di Copertina</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Articolo__c/fields/Link_Immagine_Di_Copertina__c.field-meta.xml
<CustomField>
    <fullName>Link_Immagine_Di_Copertina__c</fullName>
    <label>Link Immagine Di Copertina</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/Articolo__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <description>Voci di menu dove l&apos;articolo dovrà essere inserito</description>
    <inlineHelpText>Voci di menu dove l&apos;articolo dovrà essere inserito</inlineHelpText>
    <label>Menu</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>TFS</fullName>
            </value>
            <value>
                <fullName>TIM</fullName>
            </value>
            <value>
                <fullName>TFM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Articolo__c/fields/Riassunto__c.field-meta.xml
<CustomField>
    <fullName>Riassunto__c</fullName>
    <label>Riassunto</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Articolo__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <description>Tag dell&apos;articolo separati da virgola</description>
    <inlineHelpText>Tag dell&apos;articolo separati da virgola</inlineHelpText>
    <label>Tag</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Articolo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia di articolo</description>
    <inlineHelpText>In base alla tipologia lo considero come gruppo o articolo singolo</inlineHelpText>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Articolo</fullName>
                <default>true</default>
                <label>Articolo</label>
            </value>
            <value>
                <fullName>Circolare</fullName>
            </value>
            <value>
                <fullName>COVID19</fullName>
            </value>
            <value>
                <fullName>Gruppo</fullName>
            </value>
            <value>
                <fullName>Road2Tokyo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Articolo__c/fields/Titolo__c.field-meta.xml
<CustomField>
    <fullName>Titolo__c</fullName>
    <description>Titolo dell&apos;articolo</description>
    <inlineHelpText>Inserire il titolo dell&apos;articolo</inlineHelpText>
    <label>Titolo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo_Articolo__c/Gruppo_Articolo__c.object-meta.xml
<CustomObject>
    <label>Gruppo Articolo</label>
    <nameField>
        <displayFormat>GA-{00000000}</displayFormat>
        <label>Nome Gruppo Articolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gruppi Articoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gruppo_Articolo__c/fields/Articolo__c.field-meta.xml
<CustomField>
    <fullName>Articolo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Articolo</label>
    <referenceTo>Articolo__c</referenceTo>
    <relationshipLabel>Gruppi Articoli</relationshipLabel>
    <relationshipName>Gruppi_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo_Articolo__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gruppo</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Gruppi Articoli</relationshipLabel>
    <relationshipName>Gruppi_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente__c/fields/Cognome__c.field-meta.xml
<CustomField>
    <fullName>Cognome__c</fullName>
    <description>Cognome dell&apos;utente</description>
    <inlineHelpText>Cognome dell&apos;utente</inlineHelpText>
    <label>Cognome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome dell&apos;utente</description>
    <inlineHelpText>Nome dell&apos;utente</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/force-app/main/default/objects/Utente__c/fields/Titolo__c.field-meta.xml
<CustomField>
    <fullName>Titolo__c</fullName>
    <description>Titolo del contatto ... Dott ... Sig ...</description>
    <inlineHelpText>Titolo del contatto ... Dott ... Sig ...</inlineHelpText>
    <label>Titolo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Utente_Articolo__c/Utente_Articolo__c.object-meta.xml
<CustomObject>
    <description>Visualizzazioni, Commenti e Like in ricorsione con se stessi per poter avere anche like ai commenti e visualizzazioni ai commenti</description>
    <label>Utente Articolo</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Nome Utente Articolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utenti Articoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente_Articolo__c/fields/Articolo__c.field-meta.xml
<CustomField>
    <fullName>Articolo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Articolo associato a questo utente</description>
    <inlineHelpText>Articolo associato a questo utente</inlineHelpText>
    <label>Articolo</label>
    <referenceTo>Articolo__c</referenceTo>
    <relationshipLabel>Utenti Articoli</relationshipLabel>
    <relationshipName>Utenti_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Articolo__c/fields/Genitore__c.field-meta.xml
<CustomField>
    <fullName>Genitore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se correlato si riferisce a quel commento</description>
    <inlineHelpText>Se correlato si riferisce a quel commento</inlineHelpText>
    <label>Genitore</label>
    <referenceTo>Utente_Articolo__c</referenceTo>
    <relationshipLabel>Utenti Articoli</relationshipLabel>
    <relationshipName>Utenti_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Articolo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Commento, Like o Visualizzazione</description>
    <inlineHelpText>Commento, Like o Visualizzazione</inlineHelpText>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commento</fullName>
                <default>true</default>
                <label>Commento</label>
            </value>
            <value>
                <fullName>Like</fullName>
            </value>
            <value>
                <fullName>Visualizzazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente_Articolo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente associato a questo articolo</description>
    <inlineHelpText>Utente associato a questo articolo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Articoli</relationshipLabel>
    <relationshipName>Utenti_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/Article.cls
public class Article {
    
    public String id;
    public String author;
    public String title;
    public String excerpt;
    public String content;
    public String imageUrl;
    public String imageLink;
    public Long publishedDateTime;
    public List<String> tags = new List<String>();
    public List<String> brands = new List<String>();
    public List<ArticleComment> comments = new List<ArticleComment>();
    public List<ArticleLike> likes = new List<ArticleLike>();
    public List<ArticleView> views = new List<ArticleView>();
    public List<String> areas = new List<String>();
    public List<String> menu = new List<String>();
    public String attachment1;
    
    public Article(Articolo__c article){
        
        this.id = article.Id;
        this.author = article.Autore__r.Nome__c + ' ' + article.Autore__r.Cognome__c;
        this.title = article.Titolo__c;
        this.excerpt = article.Riassunto__c;
        this.content = article.Contenuto__c;
        this.imageUrl = article.Immagine_Di_Copertina__c;
        this.imageLink = article.Link_Immagine_Di_Copertina__c;
        this.publishedDateTime = article.Data_Ora_Pubblicazione__c.getTime();
        this.tags = article.Tag__c != null ? article.Tag__c.split(',') : tags;
        this.areas = article.Area__c != null ? article.Area__c.split(';') : areas;
        this.menu = article.Menu__c != null ? article.Menu__c.split(';') : menu;
        this.attachment1 = article.Allegato_1__c;
        
        for(Gruppo_Articolo__c articleGroup : article.Gruppi_Articoli__r){
            
            this.brands.add(articleGroup.Gruppo__r.Name);
            
        }
        
        for(Utente_Articolo__c userArticle : article.Utenti_Articoli__r){
            
            if('Commento'.equals(userArticle.Tipologia__c)){
                
                this.comments.add(new ArticleComment(userArticle));
                
            }else if('Like'.equals(userArticle.Tipologia__c)){
                
                this.likes.add(new ArticleLike(userArticle));
                
            }else if('Visualizzazione'.equals(userArticle.Tipologia__c)){
                
                this.views.add(new ArticleView(userArticle));
                
            }
            
        }
        
    }
    
}