Produzione/force-app/main/default/objects/Articolo__c/Articolo__c.object-meta.xml
<CustomObject>
    <description>Oggetto per la gestione degli articoli all&apos;interno della app</description>
    <label>Articolo</label>
    <nameField>
        <displayFormat>ART-{00000000}</displayFormat>
        <label>Nome Articolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Articoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Articolo__c/fields/Genitore__c.field-meta.xml
<CustomField>
    <fullName>Genitore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Articolo correlato</description>
    <inlineHelpText>Collegandolo ad un articolo padre creo un raggruppamento di articoli</inlineHelpText>
    <label>Genitore</label>
    <referenceTo>Articolo__c</referenceTo>
    <relationshipLabel>Articoli</relationshipLabel>
    <relationshipName>Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Articolo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia di articolo</description>
    <inlineHelpText>In base alla tipologia lo considero come gruppo o articolo singolo</inlineHelpText>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Articolo</fullName>
                <default>true</default>
                <label>Articolo</label>
            </value>
            <value>
                <fullName>Circolare</fullName>
            </value>
            <value>
                <fullName>COVID19</fullName>
            </value>
            <value>
                <fullName>Gruppo</fullName>
            </value>
            <value>
                <fullName>Road2Tokyo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Dispositivo__c/Dispositivo__c.object-meta.xml
<CustomObject>
    <description>Dispositivi collegati all&apos;utente per generazione token di sessione</description>
    <label>Dispositivo</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Nome Dispositivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispositivi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispositivo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato</description>
    <inlineHelpText>Utente collegato a questo dispositivo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Dispositivi</relationshipLabel>
    <relationshipName>Dispositivi</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/Domanda_Questionario__c.object-meta.xml
<CustomObject>
    <description>Domande che compongono il questionario</description>
    <label>Domanda Questionario</label>
    <nameField>
        <label>Nome Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domande Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia della domanda</description>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Informativo</fullName>
            </value>
            <value>
                <fullName>Testo semplice</fullName>
            </value>
            <value>
                <fullName>Testo lungo</fullName>
            </value>
            <value>
                <fullName>Numerico	Numerico</fullName>
            </value>
            <value>
                <fullName>Valutazione</fullName>
            </value>
            <value>
                <fullName>Vero/falso</fullName>
            </value>
            <value>
                <fullName>Scelta multipla</fullName>
            </value>
            <value>
                <fullName>Valutazione multipla</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Menu di selezione singol</fullName>
            </value>
            <value>
                <fullName>Opzione</fullName>
            </value>
            <value>
                <fullName>Radio con commento</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio se minore di 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Genitore__c.field-meta.xml
<CustomField>
    <fullName>Genitore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Genitore</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Gruppi</relationshipLabel>
    <relationshipName>Gruppi</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo_Articolo__c/Gruppo_Articolo__c.object-meta.xml
<CustomObject>
    <label>Gruppo Articolo</label>
    <nameField>
        <displayFormat>GA-{00000000}</displayFormat>
        <label>Nome Gruppo Articolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gruppi Articoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Gruppo_Articolo__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gruppo</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Gruppi Articoli</relationshipLabel>
    <relationshipName>Gruppi_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/TMI_RCC__c/TMI_RCC__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variabili globali per l&apos;app</description>
    <label>TMI RCC</label>
</CustomObject>

Produzione/force-app/main/default/objects/TMI_RCC__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <description>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</description>
    <inlineHelpText>Chiave segreta per la generazione / validazione dei JSON Web Token (JWT)</inlineHelpText>
    <label>Secret Key</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Non_Considerare_Analisi__c.field-meta.xml
<CustomField>
    <fullName>Non_Considerare_Analisi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Per considerare o meno opinione utente nelle analisi</description>
    <inlineHelpText>Per considerare o meno opinione utente nelle analisi</inlineHelpText>
    <label>Non Considerare Analisi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente_Articolo__c/Utente_Articolo__c.object-meta.xml
<CustomObject>
    <description>Visualizzazioni, Commenti e Like in ricorsione con se stessi per poter avere anche like ai commenti e visualizzazioni ai commenti</description>
    <label>Utente Articolo</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>Nome Utente Articolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utenti Articoli</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente_Articolo__c/fields/Genitore__c.field-meta.xml
<CustomField>
    <fullName>Genitore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se correlato si riferisce a quel commento</description>
    <inlineHelpText>Se correlato si riferisce a quel commento</inlineHelpText>
    <label>Genitore</label>
    <referenceTo>Utente_Articolo__c</referenceTo>
    <relationshipLabel>Utenti Articoli</relationshipLabel>
    <relationshipName>Utenti_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Articolo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Commento, Like o Visualizzazione</description>
    <inlineHelpText>Commento, Like o Visualizzazione</inlineHelpText>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commento</fullName>
                <default>true</default>
                <label>Commento</label>
            </value>
            <value>
                <fullName>Like</fullName>
            </value>
            <value>
                <fullName>Visualizzazione</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente_Articolo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente associato a questo articolo</description>
    <inlineHelpText>Utente associato a questo articolo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Articoli</relationshipLabel>
    <relationshipName>Utenti_Articoli</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente_Gruppo__c/Utente_Gruppo__c.object-meta.xml
<CustomObject>
    <label>Utente Gruppo</label>
    <nameField>
        <label>Nome Utente Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente_Gruppo__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gruppo</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Utenti Gruppi</relationshipLabel>
    <relationshipName>Utenti_Gruppi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente_Gruppo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utente Custom</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Gruppi</relationshipLabel>
    <relationshipName>Utenti_Gruppi</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/ArticleResourceTest.cls
@isTest
public class ArticleResourceTest {
    
    static String endpoint = '/services/apexrest/articles';
    
    @testSetup
    static void setup(){
        
        TMI_RCC__c settings = new TMI_RCC__c();
        
        settings.Secret_Key__c = 'secret';
        
        insert settings;
        
        App__c app = new App__c();
        
        insert app;
        
        Utente__c author = new Utente__c();
        
        author.Nickname__c = 'author';
        author.Password__c = 'author';
        author.App__c = app.Id;
        
        insert author;
        
        Utente__c user = new Utente__c();
        
        user.Nickname__c = 'nickname';
        user.Password__c = 'password';
        user.App__c = app.Id;
        user.Tipologia__c = 'Manager';
        user.Non_Considerare_Analisi__c = false;
        
        insert user;
        
        Gruppo__c mainGroup = new Gruppo__c();
        
        mainGroup.Name = 'Main';
        
        insert mainGroup;
        
        Gruppo__c brandGroup = new Gruppo__c();
        
        brandGroup.Name = 'Brand 1';
        brandGroup.Tipologia__c = 'Marchio';
        brandGroup.Genitore__c = mainGroup.Id;
        
        insert brandGroup;
        
        Gruppo__c zoneGroup = new Gruppo__c();
        
        zoneGroup.Name = 'Zone 1';
        zoneGroup.Tipologia__c = 'Zona';
        zoneGroup.Genitore__c = brandGroup.Id;
        
        insert zoneGroup;
        
        Utente_Gruppo__c userGroup = new Utente_Gruppo__c();
        
        userGroup.Utente__c = user.Id;
        userGroup.Gruppo__c = brandGroup.Id;
        
        insert userGroup;
                
        Insieme_Opzioni_Domanda__c questionOptionSet = new Insieme_Opzioni_Domanda__c();
        
        insert questionOptionSet;
        
        Domanda_questionario__c question = new Domanda_questionario__c();
        
        question.Insieme_Opzioni_Domanda__c = questionOptionSet.Id;
        question.Data_Ora_Inizio__c = System.now();
        question.Data_Ora_Fine__c = System.now().addDays(1);
        
        insert question;
        
        Opzione_Domanda__c questionOption = new Opzione_Domanda__c();
        
        questionOption.Insieme_Opzioni_Domanda__c = questionOptionSet.Id;
        
        insert questionOption;
        
        Articolo__c article = new Articolo__c();
        
        article.Contenuto__c = 'content';
        article.Titolo__c = 'title';
        article.Tag__c = 'tag1,tag2';
        article.Autore__c = author.Id;
        article.Data_Ora_Pubblicazione__c = System.now();
        article.Riassunto__c = 'excerpt';
        article.Tipologia__c = 'Articolo';
        article.Menu__c = 'Toyota;Lexus';
        
        insert article;
        
        Gruppo_Articolo__c contentGroup = new Gruppo_Articolo__c();
        
        contentGroup.Articolo__c = article.Id;
        contentGroup.Gruppo__c = brandGroup.Id;
        
        insert contentGroup;
        
        Utente_Articolo__c userLike = new Utente_Articolo__c();
        
        userLike.Articolo__c = article.Id;
        userLike.Tipologia__c = 'Like';
        userLike.Utente__c = user.Id;
        
        Utente_Articolo__c userView = new Utente_Articolo__c();
        
        userLike.Articolo__c = article.Id;
        userLike.Tipologia__c = 'Visualizzazione';
        userLike.Utente__c = user.Id;
        
        insert new List<Utente_Articolo__c>{userLike, userView};
        
        
        
    }
    
    static App__c getApp(){
        
        return [SELECT Id FROM App__c LIMIT 1];
        
    }
    
    static Utente__c getUser(){
        
        return [SELECT Id FROM Utente__c WHERE Nickname__c = 'nickname' LIMIT 1];
        
    }
    
    static Domanda_questionario__c getQuestion(){
        
        return [SELECT Id FROM Domanda_questionario__c LIMIT 1];
        
    }
    
    static Articolo__c getArticle(){
        
        return [SELECT Id FROM Articolo__c LIMIT 1];
        
    }
    
    @isTest
    static void testGetArticlesUnauthtenticated(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'GET';
        
        req.requestBody = null;
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doGet();
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testGetArticles(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'GET';
        
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        req.requestBody = null;
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doGet();
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testGetArticlesMenu(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint + '/menu';
        req.httpMethod = 'GET';
        
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        req.requestBody = null;
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doGet();
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testCountArticles(){
        
        Test.startTest();
        
        ArticleResource.countAllUserArticles(getUser().Id);
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testFindArticleById(){
        
        Test.startTest();
        
        ArticleResource.findArticleById(getArticle().Id);
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testGetLatestContent(){
        
        Utente__c u = getUser();
        
        List<Gruppo__c> childGroups = UserResource.getUserGroupChildren(u.Id);
        
        Set<Id> groupsIds = new Set<Id>();
        
        for(Gruppo__c g : childGroups){
            
            groupsIds.add(g.Id);
            
        }
        
        System.debug(groupsIds);
        
        Test.startTest();
        
        ArticleResource.getLatestContent(u.Id, groupsIds);
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testGetMostLikedAndViwedContents(){
        
        Utente__c u = getUser();
        
        List<Gruppo__c> childGroups = UserResource.getUserGroupChildren(u.Id);
        
        Set<Id> groupsIds = new Set<Id>();
        
        for(Gruppo__c g : childGroups){
            
            groupsIds.add(g.Id);
            
        }
        
        Test.startTest();
        
        ArticleResource.getMostLikedAndViwedContents(u.Id, groupsIds);
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testPostArticlesUnauthtenticated(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'POST';
        
        req.requestBody = null;
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doPost('asdasd');
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testPostArticlesWithoutBody(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'POST';
        
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        req.requestBody = null;
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doPost('asdasd');
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testPostArticlesWithEmptyBody(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'POST';
        
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        req.requestBody = Blob.valueOf('');
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doPost('asdasd');
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testPostArticlesWithWrongBody(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'POST';
        
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        req.requestBody = Blob.valueOf('{ikuasdcgiuas""gdifasd}');
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doPost('asdasd');
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testPostArticleView(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint + '/' + getArticle().Id;
        req.httpMethod = 'POST';
        
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        req.requestBody = Blob.valueOf('{ikuasdcgiuas""gdifasd}');
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doPost('view');
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testPostArticleLike(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint + '/' + getArticle().Id;
        req.httpMethod = 'POST';
        
        JWT jwt = new JWT();
        jwt.setKey('secret');
        
        Dispositivo__c device = new Dispositivo__c();
        
        device.Dispositivo__c = 'deviceId';
        device.Firebase_Token__c = 'firebaseToken';
        device.Token__c = jwt.encode(new Map<String, Object>{'id' => getUser().Id}, 60 * 5);
        device.Utente__c = getUser().Id;
        
        insert device;
        
        req.addHeader('x-bearer-token', jwt.encode(null, 60));
        req.addHeader('x-device-id', 'deviceId');
        req.addHeader('x-firebase-token', 'firebaseToken');
        req.addHeader('x-auth-token', device.Token__c);
        req.addHeader('x-app-id', getApp().Id);
        
        req.requestBody = Blob.valueOf('{ikuasdcgiuas""gdifasd}');
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        ArticleResource.doPost('like');
        
        System.debug(res.responseBody.toString());
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }

}