Produzione/force-app/main/default/objects/Domanda_Questionario__c/Domanda_Questionario__c.object-meta.xml
<CustomObject>
    <description>Domande che compongono il questionario</description>
    <label>Domanda Questionario</label>
    <nameField>
        <label>Nome Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domande Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Domanda_questionario__c/fields/Albero__c.field-meta.xml
<CustomField>
    <fullName>Albero__c</fullName>
    <label>Albero</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nessuno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/force-app/main/default/objects/Domanda_questionario__c/fields/Considerare__c.field-meta.xml
<CustomField>
    <fullName>Considerare__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Considerare</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Data_Ora_Fine__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Fine__c</fullName>
    <label>Data Ora Fine</label>
    <type>DateTime</type>
</CustomField>

Sandbox/force-app/main/default/objects/Domanda_questionario__c/fields/Data_Ora_Inizio__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Inizio__c</fullName>
    <label>Data Ora Inizio</label>
    <type>DateTime</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Domanda_IT__c.field-meta.xml
<CustomField>
    <fullName>Domanda_IT__c</fullName>
    <label>Domanda IT</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

Sandbox/force-app/main/default/objects/Domanda_questionario__c/fields/Etichetta_IT__c.field-meta.xml
<CustomField>
    <fullName>Etichetta_IT__c</fullName>
    <description>Etichetta per identificare la domanda</description>
    <inlineHelpText>Etichetta per identificare la domanda. Es. titolo della domanda</inlineHelpText>
    <label>Etichetta IT</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Insieme_Opzioni_Domanda__c.field-meta.xml
<CustomField>
    <fullName>Insieme_Opzioni_Domanda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insieme Opzioni Domanda</label>
    <referenceTo>Insieme_Opzioni_Domanda__c</referenceTo>
    <relationshipLabel>Domande questionario</relationshipLabel>
    <relationshipName>Domande_questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Obbligatoria__c.field-meta.xml
<CustomField>
    <fullName>Obbligatoria__c</fullName>
    <defaultValue>false</defaultValue>
    <description>La domanda è obbligatoria (compare asterisco)</description>
    <label>Obbligatoria</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine della domanda all&apos;interno della pagina/sezione</description>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Questionario__c.field-meta.xml
<CustomField>
    <fullName>Questionario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Questionario a cui appartiene la domanda</description>
    <label>Questionario</label>
    <referenceTo>Questionario__c</referenceTo>
    <relationshipLabel>Domande Questionario</relationshipLabel>
    <relationshipName>Domande_Questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Domanda_questionario__c/fields/Raggruppamento__c.field-meta.xml
<CustomField>
    <fullName>Raggruppamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raggruppamento</label>
    <referenceTo>Raggruppamento__c</referenceTo>
    <relationshipLabel>Domande questionario</relationshipLabel>
    <relationshipName>Domande_questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Suggerimento__c.field-meta.xml
<CustomField>
    <fullName>Suggerimento__c</fullName>
    <label>Suggerimento</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia della domanda</description>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Informativo</fullName>
            </value>
            <value>
                <fullName>Testo semplice</fullName>
            </value>
            <value>
                <fullName>Testo lungo</fullName>
            </value>
            <value>
                <fullName>Numerico	Numerico</fullName>
            </value>
            <value>
                <fullName>Valutazione</fullName>
            </value>
            <value>
                <fullName>Vero/falso</fullName>
            </value>
            <value>
                <fullName>Scelta multipla</fullName>
            </value>
            <value>
                <fullName>Valutazione multipla</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Menu di selezione singol</fullName>
            </value>
            <value>
                <fullName>Opzione</fullName>
            </value>
            <value>
                <fullName>Radio con commento</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio se minore di 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gruppo__c/fields/Colore__c.field-meta.xml
<CustomField>
    <fullName>Colore__c</fullName>
    <description>Colore associato al gruppo</description>
    <inlineHelpText>Colore associato al gruppo</inlineHelpText>
    <label>Colore</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</description>
    <inlineHelpText>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</inlineHelpText>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Insieme_Opzioni_Domanda__c/Insieme_Opzioni_Domanda__c.object-meta.xml
<CustomObject>
    <label>Insieme Opzioni Domanda</label>
    <nameField>
        <label>Nome Insieme Opzioni Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insiemi Opzioni Domande</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Opzione_Domanda__c/Opzione_Domanda__c.object-meta.xml
<CustomObject>
    <label>Opzione Domanda</label>
    <nameField>
        <label>Nome Opzione Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opzioni Domande</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Insieme_Opzioni_Domanda__c.field-meta.xml
<CustomField>
    <fullName>Insieme_Opzioni_Domanda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insieme Opzioni Domanda</label>
    <referenceTo>Insieme_Opzioni_Domanda__c</referenceTo>
    <relationshipLabel>Opzioni Domande</relationshipLabel>
    <relationshipName>Opzioni_Domande</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <label>Ordine</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Raggruppamento__c/Raggruppamento__c.object-meta.xml
<CustomObject>
    <label>Raggruppamento</label>
    <nameField>
        <label>Nome Raggruppamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raggruppamenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Raggruppamento__c/fields/Etichetta_IT__c.field-meta.xml
<CustomField>
    <fullName>Etichetta_IT__c</fullName>
    <label>Etichetta IT</label>
    <type>TextArea</type>
</CustomField>

Sandbox/force-app/main/default/objects/Raggruppamento__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gruppo</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Raggruppamenti</relationshipLabel>
    <relationshipName>Raggruppamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raggruppamento__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indice</fullName>
            </value>
            <value>
                <fullName>Raggruppamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/Risposta_Questionario__c.object-meta.xml
<CustomObject>
    <description>Risposte del questionario</description>
    <label>Risposta Questionario</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Nome Risposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risposte Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Domanda_Questionario__c.field-meta.xml
<CustomField>
    <fullName>Domanda_Questionario__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Domanda a cui ha risposto</description>
    <label>Domanda Questionario</label>
    <referenceTo>Domanda_Questionario__c</referenceTo>
    <relationshipLabel>Risposte Questionario</relationshipLabel>
    <relationshipName>Risposte_Questionario</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/QuestionData.cls
public class QuestionData {
    
    public String id;
    public String brand;
    public String surveyId;
    public String groupingId;
    public String tree;
    public String question;
    public String label;
    public String questionType;
    public String helpText;
    public Long startDateTime;
    public Long endDateTime;
    public Boolean additional;
    public Boolean visible;
    public Boolean mandatory;
    public Boolean toConsider;
    public Decimal order;
    public Decimal totalAnswers;
    public List<QuestionOptionData> options = new List<QuestionOptionData>();
    public String color;
    
    public QuestionData(Domanda_questionario__c question, List<Opzione_Domanda__c> questionsOptions){
        
        this.id = question.Id;
        this.surveyId = question.Questionario__c;
        this.groupingId = question.Raggruppamento__c;
        this.tree = question.Albero__c;
        this.question = question.Domanda_IT__c;
        this.label = question.Etichetta_IT__c;
        this.questionType = question.Tipologia__c;
        this.helpText = question.Suggerimento__c;
        this.color = question.Raggruppamento__r.Gruppo__r.Colore__c;
        
        if(question.Data_Ora_Inizio__c != null){
            
        	this.startDateTime = question.Data_Ora_Inizio__c.getTime();
            
        }
        
        if(question.Data_Ora_Fine__c != null){
            
        	this.endDateTime = question.Data_Ora_Fine__c.getTime();
            
        }
        
        this.visible = question.Visibile__c;
        this.mandatory = question.Obbligatoria__c;
        this.toConsider = question.Considerare__c;
        this.order = question.Ordine__c;
        
        if(question.Risposte_questionario__r != null){
        
            this.totalAnswers = question.Risposte_questionario__r.size();
            
        }
        
        for(Opzione_Domanda__c qo : questionsOptions){
            
            if(qo.Insieme_Opzioni_Domanda__c != null && question.Insieme_Opzioni_Domanda__c != null && qo.Insieme_Opzioni_Domanda__c == question.Insieme_Opzioni_Domanda__c){
                
                this.options.add(new QuestionOptionData(qo));
                
            }
            
        }
        
    }
    
}