Produzione/force-app/main/default/objects/Domanda_Questionario__c/Domanda_Questionario__c.object-meta.xml
<CustomObject>
    <description>Domande che compongono il questionario</description>
    <label>Domanda Questionario</label>
    <nameField>
        <label>Nome Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domande Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/Risposta_Questionario__c.object-meta.xml
<CustomObject>
    <description>Risposte del questionario</description>
    <label>Risposta Questionario</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Nome Risposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risposte Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Risposta_questionario__c/fields/Data_Ora_Risposta__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Risposta__c</fullName>
    <label>Data Ora Risposta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Domanda_Questionario__c.field-meta.xml
<CustomField>
    <fullName>Domanda_Questionario__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Domanda a cui ha risposto</description>
    <label>Domanda Questionario</label>
    <referenceTo>Domanda_Questionario__c</referenceTo>
    <relationshipLabel>Risposte Questionario</relationshipLabel>
    <relationshipName>Risposte_Questionario</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Risposta_questionario__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utente Custom</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Risposte questionario</relationshipLabel>
    <relationshipName>Risposte_questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Valore_Numerico__c</fullName>
    <description>Eventuale risposta numerica</description>
    <label>Valore Numerico</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Testuale__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale__c</fullName>
    <description>Eventuale risposta testuale</description>
    <label>Valore Testuale</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Testuale_Lungo__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale_Lungo__c</fullName>
    <description>Eventuale risposta testuale lunga</description>
    <label>Valore Testuale Lungo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Produzione/force-app/main/default/classes/AnswerData.cls
public class AnswerData {
    
    public String id;
    public String userId;
    public String questionId;
    public Decimal numericValue;
    public String textValue;
    public String longTextValue;
    public Long answerDateTime;
    
    public AnswerData(){ }
    
    public void fromAnswer(Risposta_questionario__c answer){
        
        this.id = answer.Id;
        this.userId = answer.Utente__c;
        this.questionId = answer.Domanda_questionario__c;
        this.numericValue = answer.Valore_Numerico__c;
        this.textValue = answer.Valore_Testuale__c;
        this.longTextValue = answer.Valore_Testuale_Lungo__c;
        this.answerDateTime = answer.Data_Ora_Risposta__c.getTime();
        
    }
    
    public void fromJson(String jsonString){
        
        Map<String, Object> decoded = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
            
        this.id = decoded.containsKey('id') ? (String) decoded.get('id') : null;
        this.userId = decoded.containsKey('userId') ? (String) decoded.get('userId') : null;
        this.questionId = decoded.containsKey('questionId') ? (String) decoded.get('questionId') : null;
        this.numericValue = decoded.containsKey('numericValue') ? (Decimal) decoded.get('numericValue') : null;
        this.textValue = decoded.containsKey('textValue') ? (String) decoded.get('textValue') : null;
        this.longTextValue = decoded.containsKey('longTextValue') ? (String) decoded.get('longTextValue') : null;
        this.answerDateTime = decoded.containsKey('answerDateTime') ? (Long) decoded.get('answerDateTime') : null;
        
    }

}