Produzione/force-app/main/default/objects/Domanda_Questionario__c/Domanda_Questionario__c.object-meta.xml
<CustomObject>
    <description>Domande che compongono il questionario</description>
    <label>Domanda Questionario</label>
    <nameField>
        <label>Nome Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domande Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Domanda_IT__c.field-meta.xml
<CustomField>
    <fullName>Domanda_IT__c</fullName>
    <label>Domanda IT</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Insieme_Opzioni_Domanda__c.field-meta.xml
<CustomField>
    <fullName>Insieme_Opzioni_Domanda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insieme Opzioni Domanda</label>
    <referenceTo>Insieme_Opzioni_Domanda__c</referenceTo>
    <relationshipLabel>Domande questionario</relationshipLabel>
    <relationshipName>Domande_questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Obbligatoria__c.field-meta.xml
<CustomField>
    <fullName>Obbligatoria__c</fullName>
    <defaultValue>false</defaultValue>
    <description>La domanda è obbligatoria (compare asterisco)</description>
    <label>Obbligatoria</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Obbligatoria_Per_Risultati__c.field-meta.xml
<CustomField>
    <fullName>Obbligatoria_Per_Risultati__c</fullName>
    <description>Se settato, rende obbligatoria la risposta per visualizzare la specifica schermata dei risultati</description>
    <inlineHelpText>Se settato, rende obbligatoria la risposta per visualizzare la specifica schermata dei risultati</inlineHelpText>
    <label>Obbligatoria Per Risultati</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dealer Dashboard</fullName>
            </value>
            <value>
                <fullName>Dealer Altri risultati</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine della domanda all&apos;interno della pagina/sezione</description>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Questionario__c.field-meta.xml
<CustomField>
    <fullName>Questionario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Questionario a cui appartiene la domanda</description>
    <label>Questionario</label>
    <referenceTo>Questionario__c</referenceTo>
    <relationshipLabel>Domande Questionario</relationshipLabel>
    <relationshipName>Domande_Questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Domanda_questionario__c/fields/Raggruppamento__c.field-meta.xml
<CustomField>
    <fullName>Raggruppamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raggruppamento</label>
    <referenceTo>Raggruppamento__c</referenceTo>
    <relationshipLabel>Domande questionario</relationshipLabel>
    <relationshipName>Domande_questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia della domanda</description>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Informativo</fullName>
            </value>
            <value>
                <fullName>Testo semplice</fullName>
            </value>
            <value>
                <fullName>Testo lungo</fullName>
            </value>
            <value>
                <fullName>Numerico	Numerico</fullName>
            </value>
            <value>
                <fullName>Valutazione</fullName>
            </value>
            <value>
                <fullName>Vero/falso</fullName>
            </value>
            <value>
                <fullName>Scelta multipla</fullName>
            </value>
            <value>
                <fullName>Valutazione multipla</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Menu di selezione singol</fullName>
            </value>
            <value>
                <fullName>Opzione</fullName>
            </value>
            <value>
                <fullName>Radio con commento</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio se minore di 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gruppo__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</description>
    <inlineHelpText>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</inlineHelpText>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/force-app/main/default/objects/Opzione_Domanda__c/Opzione_Domanda__c.object-meta.xml
<CustomObject>
    <label>Opzione Domanda</label>
    <nameField>
        <label>Nome Opzione Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opzioni Domande</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Opzione_Domanda__c/fields/Etichetta_Risultati_IT__c.field-meta.xml
<CustomField>
    <fullName>Etichetta_Risultati_IT__c</fullName>
    <label>Etichetta Risultati IT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Insieme_Opzioni_Domanda__c.field-meta.xml
<CustomField>
    <fullName>Insieme_Opzioni_Domanda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insieme Opzioni Domanda</label>
    <referenceTo>Insieme_Opzioni_Domanda__c</referenceTo>
    <relationshipLabel>Opzioni Domande</relationshipLabel>
    <relationshipName>Opzioni_Domande</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Opzione_Domanda_IT__c.field-meta.xml
<CustomField>
    <fullName>Opzione_Domanda_IT__c</fullName>
    <label>Opzione Domanda IT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <label>Ordine</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Valore_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Valore_Numerico__c</fullName>
    <label>Valore Numerico</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opzione_Domanda__c/fields/Valore_Testuale__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale__c</fullName>
    <label>Valore Testuale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Raggruppamento__c/Raggruppamento__c.object-meta.xml
<CustomObject>
    <label>Raggruppamento</label>
    <nameField>
        <label>Nome Raggruppamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raggruppamenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Raggruppamento__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gruppo</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Raggruppamenti</relationshipLabel>
    <relationshipName>Raggruppamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raggruppamento__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indice</fullName>
            </value>
            <value>
                <fullName>Raggruppamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/Risposta_Questionario__c.object-meta.xml
<CustomObject>
    <description>Risposte del questionario</description>
    <label>Risposta Questionario</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Nome Risposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risposte Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Risposta_questionario__c/fields/Data_Ora_Risposta__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Risposta__c</fullName>
    <label>Data Ora Risposta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Domanda_Questionario__c.field-meta.xml
<CustomField>
    <fullName>Domanda_Questionario__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Domanda a cui ha risposto</description>
    <label>Domanda Questionario</label>
    <referenceTo>Domanda_Questionario__c</referenceTo>
    <relationshipLabel>Risposte Questionario</relationshipLabel>
    <relationshipName>Risposte_Questionario</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Risposta_questionario__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utente Custom</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Risposte questionario</relationshipLabel>
    <relationshipName>Risposte_questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Valore_Numerico__c</fullName>
    <description>Eventuale risposta numerica</description>
    <label>Valore Numerico</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Testuale__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale__c</fullName>
    <description>Eventuale risposta testuale</description>
    <label>Valore Testuale</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Testuale_Lungo__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale_Lungo__c</fullName>
    <description>Eventuale risposta testuale lunga</description>
    <label>Valore Testuale Lungo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Utente_Master__c.field-meta.xml
<CustomField>
    <fullName>Utente_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</description>
    <inlineHelpText>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</inlineHelpText>
    <label>Utente Master</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Master</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/QuestionResource.cls
@RestResource(urlMapping='/questions/*')
global class QuestionResource {
    
    @HttpPost
    global static void doPost(/*String id, String userId, String questionId, Integer numericValue, String textValue, String longTextValue*/){
                
        CustomAuthentication ca = new CustomAuthentication(RestContext.request, RestContext.response);
        
        if(!ca.authenticate()){
            
            ca.getResponse().send();
        
            return;
            
        }
        
        CustomResponse res = new CustomResponse(RestContext.response);
        
        //String jsonBody = RestContext.request.requestBody.toString();
                
        AnswerData userAnswer = new AnswerData();        
        Risposta_questionario__c newAnswer = new Risposta_questionario__c();
        
        if(RestContext.request.requestBody == null){  
            
            res.setStatusCode(500);
            res.setBody(new Map<String, Object>{'error' => 'Request body missing.'});
            res.send();
            
            return;
            
        }          
            
        String body = RestContext.request.requestBody.toString();
        
        if(String.isEmpty(body)){
            
            res.setStatusCode(500);
            res.setBody(new Map<String, Object>{'error' => 'Request body is empty.'});
            res.send();
            
            return;
            
        }
        
        try{
        
            userAnswer.fromJson(body);
            
        }catch(Exception ex){
            
            res.setStatusCode(500);
            res.setBody(new Map<String, Object>{'error' => 'Malformed json.'});
            res.send();
            
            return;
            
        }
        
        if(String.isEmpty(userAnswer.questionId)){
            
            res.setStatusCode(500);
            res.setBody(new Map<String, Object>{'error' => 'Question id is missing.'});
            res.send();
            
            return;
            
        }
        
        Domanda_questionario__c question = [SELECT Id, Tipologia__c, Obbligatoria__c FROM Domanda_questionario__c WHERE Id = :userAnswer.questionId LIMIT 1];
        
        if(question.Obbligatoria__c && userAnswer.numericValue == null && String.isBlank(userAnswer.textValue)){
            
            res.setStatusCode(500);
            res.setBody(new Map<String, Object>{'error' => 'Domanda obbligatoria'});
            res.send();
            
            return;
            
        }
        
        if('Radio con commento obbligatorio'.equalsIgnoreCase(question.Tipologia__c)){
            
            if(String.isBlank(userAnswer.longTextValue)){
                
                res.setStatusCode(500);
                res.setBody(new Map<String, Object>{'error' => 'Commento obbligatorio'});
                res.send();
                
                return;
                
            }
            
            
        }else if('Radio con commento obbligatorio se minore di 3'.equalsIgnoreCase(question.Tipologia__c)){
            
            if(String.isBlank(userAnswer.longTextValue) && userAnswer.numericValue < 3){
                
                res.setStatusCode(500);
                res.setBody(new Map<String, Object>{'error' => 'Commento obbligatorio'});
                res.send();
                
                return;
                
            }
            
        }
        
        userAnswer.userId = ca.getUser().Id;
        userAnswer.answerDateTime = System.now().getTime();
            
        newAnswer.Utente__c = userAnswer.userId;
        newAnswer.Domanda_questionario__c = userAnswer.questionId;
        newAnswer.Valore_Numerico__c = userAnswer.numericValue;
        newAnswer.Valore_Testuale__c = userAnswer.textValue;
        newAnswer.Valore_Testuale_Lungo__c = userAnswer.longTextValue;
        newAnswer.Data_Ora_Risposta__c = Datetime.newInstance(userAnswer.answerDateTime);
        
        if(!ca.isStealth() && (newAnswer.Valore_Numerico__c != null || newAnswer.Valore_Testuale__c != null)){
            insert newAnswer;
        }
        
        AnswerData answerData = new AnswerData();
        
        answerData.fromAnswer(newAnswer);
        
        res.setStatusCode(200);
        res.setBody(answerData);
        res.send();
        
        return;
        
    }
    
    @HttpGet
    global static void doGet(){
        
        String path = RestContext.request.requestURI.substring(RestContext.request.requestURI.lastIndexOf('/')+1);
        
        CustomAuthentication ca = new CustomAuthentication(RestContext.request, RestContext.response);
        
        if(!ca.authenticate()){
            
            ca.getResponse().send();
        
            return;
            
        }
        
        CustomResponse res = new CustomResponse(RestContext.response);
        
        Utente__c u = ca.getUser();
        Id userId = u.Id;
        
        if('get_count'.equals(path)){
            
            String target = RestContext.request.params.get('target');
            
            userId = u.Utente_Master__c != null ? u.Utente_Master__c : u.Id;
            
            res.setStatusCode(200);
            res.setBody(buildGetCountBody(getUserQuestionsCountByUserId(userId, target)));
            
        }else{
            
            List<Domanda_Questionario__c> userQuestions = findAllUserQuestionsByUserId(userId);
            List<Opzione_Domanda__c> questionsOptions = findQuestionsOptionsByQuestionsIds(userQuestions);
            
            res.setStatusCode(200);
            res.setBody(buildFindAllQuestionsBody(userQuestions, questionsOptions));
            
        }        
        
        res.send();
        
    }
    
    private static Object buildGetCountBody(Integer count){
        
        return new Map<String, Object>{'count' => count};
        
    }
    
    private static Object buildFindAllQuestionsBody(List<Domanda_Questionario__c> questions, List<Opzione_Domanda__c> questionsOptions){
        
        List<Object> jsonQuestions = new List<Object>();
        
        for(Domanda_Questionario__c q : questions){
            
            String brand = '';
            
            QuestionData newQuestion = new QuestionData(q, questionsOptions);
            
            if(String.isNotBlank(q.Raggruppamento__r.Gruppo__r.Name)){
                
                brand = q.Raggruppamento__r.Gruppo__r.Name.toLowerCase();
                
            }
            
            newQuestion.brand = brand;
            
            jsonQuestions.add(newQuestion);
            
        }
        
        return jsonQuestions;
        
    }
    
    private static List<Opzione_Domanda__c> findQuestionsOptionsByQuestionsIds(List<Domanda_Questionario__c> userQuestions){
        
        Set<Id> groupsIds = new Set<Id>();
        
        for(Domanda_Questionario__c question : userQuestions){
            
            groupsIds.add(question.Insieme_Opzioni_Domanda__c);
            
        }
        
        return [SELECT Id, Etichetta_Risultati_IT__c, Opzione_Domanda_IT__c, Valore_Numerico__c, Valore_Testuale__c, 
                Insieme_Opzioni_Domanda__c
                FROM Opzione_Domanda__c 
                WHERE Insieme_Opzioni_Domanda__c IN :groupsIds ORDER BY Ordine__c, Valore_Numerico__c DESC];
        
    }
    
    public static Integer getUserQuestionsCountByUserId(Id userId, String target){
        
        //Set<Id> groups = RCCUtils.findUserGroupsByUserId(userId, false);
        
        Set<Id> groups = new Set<Id>();
        
        List<Gruppo__c> userGroups = UserResource.getUserGroupAncestors(userId);
        
        for(Gruppo__c g : userGroups){
            
            groups.add(g.Id);
            
        }
        
        return countQuestionsByGroupIds(groups, userId, target);
        
    }
    
    public static Boolean thereAreNewQuestions(Set<Id> groupIds, String target){
        
        DateTime currentDateTime = System.now();
        Integer currentMonth = currentDateTime.month();
        Integer currentYear = currentDateTime.year();
        Integer currentDay = currentDateTime.day();
        
        Date periodStart = Date.newInstance(currentYear, currentMonth, currentDay >= 15 ? 15 : 1);
        Date periodEnd = Date.newInstance(periodStart.year(), periodStart.month(), currentDay >= 15 ? 1 : 15);
        
        periodEnd.addMonths(currentDay >= 15 ? 1 : 0);
        
        Integer counter = [SELECT COUNT() FROM Domanda_Questionario__c 
                           WHERE Raggruppamento__r.Gruppo__c IN :groupIds AND Obbligatoria_Per_Risultati__c != null
                           AND (Raggruppamento__r.Visualizzabile_Da_Dealer_In__c = :target OR Raggruppamento__r.Genitore__r.Visualizzabile_Da_Dealer_In__c = :target)
                           AND Data_Ora_Inizio__c <= :currentDatetime AND Data_Ora_Inizio__c >= :periodStart AND Data_Ora_Inizio__c <= :periodEnd];
        
        return counter > 0;
        
    }
    
    private static List<Domanda_Questionario__c> findAllUserQuestionsByUserId(Id userId){
        
        //Set<Id> groups = RCCUtils.findUserGroupsByUserId(userId, false);
        
        Set<Id> groups = new Set<Id>();
        
        List<Gruppo__c> userGroups = UserResource.getUserGroupAncestors(userId);
        
        for(Gruppo__c g : userGroups){
            
            groups.add(g.Id);
            
        }
        
        return findQuestionsByGroupIds(groups, userId);               
        
    }
    
    private static Integer countQuestionsByGroupIds(Set<Id> groupIds, Id userId, String target){
        
        Datetime currentDatetime = System.now();
        
        if(String.isBlank(target)){
        
            return [SELECT COUNT() FROM Domanda_Questionario__c 
                    WHERE Id NOT IN (SELECT Domanda_questionario__c FROM Risposta_questionario__c WHERE Utente__c = :userId) 
                    AND Raggruppamento__r.Gruppo__c IN :groupIds
                    AND Data_Ora_Inizio__c <= :currentDatetime AND Data_Ora_Fine__c >= :currentDatetime];
            
        }
        
        return [SELECT COUNT() FROM Domanda_Questionario__c 
                WHERE Id NOT IN (SELECT Domanda_questionario__c FROM Risposta_questionario__c WHERE Utente__c = :userId) 
                AND Raggruppamento__r.Gruppo__c IN :groupIds /* AND Obbligatoria__c = true */ AND Obbligatoria_Per_Risultati__c != null
                AND (Raggruppamento__r.Visualizzabile_Da_Dealer_In__c = :target OR Raggruppamento__r.Genitore__r.Visualizzabile_Da_Dealer_In__c = :target)
                AND Data_Ora_Inizio__c <= :currentDatetime AND Data_Ora_Fine__c >= :currentDatetime];
        
    }
    
    private static List<Domanda_Questionario__c> findQuestionsByGroupIds(Set<Id> groupIds, Id userId){
        
        Datetime currentDatetime = System.now();
        
        return [SELECT Id, Etichetta_IT__c, Domanda_IT__c, Questionario__c, Raggruppamento__c, Albero__c, Tipologia__c, Obbligatoria__c,
                Suggerimento__c, Data_Ora_Inizio__c, Data_Ora_Fine__c, Visibile__c, Considerare__c, Ordine__c, Insieme_Opzioni_Domanda__c,
                (SELECT Id, Utente__c FROM Risposte_questionario__r), Raggruppamento__r.Gruppo__r.Name, Raggruppamento__r.Gruppo__r.Colore__c
                FROM Domanda_Questionario__c 
                WHERE Id NOT IN (SELECT Domanda_questionario__c FROM Risposta_questionario__c WHERE Utente__c = :userId) 
                AND Raggruppamento__r.Gruppo__c IN :groupIds
                AND Data_Ora_Inizio__c <= :currentDatetime AND Data_Ora_Fine__c >= :currentDatetime
                ORDER BY Priorita__c ASC, Data_Ora_Inizio__c ASC, Ordine__c ASC];
        
    }
    
    public static List<Domanda_Questionario__c> getCurrentQuestionsByGroupIds(Set<Id> groupsIds){
        
        Datetime currentDatetime = System.now();
        
        List<Gruppo__c> groups = [SELECT Id, Gruppo_Master__c FROM Gruppo__c WHERE Id IN :groupsIds];
        
        for(Gruppo__c g : groups){
            if(g.Gruppo_Master__c != null){
                groupsIds.add(g.Gruppo_Master__c);
            }
        }
        
        return [SELECT Id, Etichetta_IT__c, Domanda_IT__c, Questionario__c, Raggruppamento__c, Albero__c, Tipologia__c, Obbligatoria__c,
                Suggerimento__c, Data_Ora_Inizio__c, Data_Ora_Fine__c, Visibile__c, Considerare__c, Ordine__c, Insieme_Opzioni_Domanda__c,
                (SELECT Id, Utente__c, Valore_Numerico__c FROM Risposte_questionario__r), Raggruppamento__r.Gruppo__r.Name, Raggruppamento__r.Gruppo__r.Colore__c, Raggruppamento__r.Etichetta_IT__c
                FROM Domanda_Questionario__c 
                WHERE Raggruppamento__r.Gruppo__c IN :groupsIds
                AND Data_Ora_Inizio__c <= :currentDatetime AND Data_Ora_Fine__c >= :currentDatetime
                ORDER BY Priorita__c ASC, Data_Ora_Inizio__c ASC, Ordine__c ASC];
        
    }
    
    public static List<Domanda_Questionario__c> getCurrentQuestionsByGroupIdsAndUserPermissions(Set<Id> groupsIds, List<String> userPermissions){
        
        Datetime currentDatetime = System.now();
        
        List<Gruppo__c> groups = [SELECT Id, Gruppo_Master__c FROM Gruppo__c WHERE Id IN :groupsIds];
        
        for(Gruppo__c g : groups){
            if(g.Gruppo_Master__c != null){
                groupsIds.add(g.Gruppo_Master__c);
            }
        }
        
        return [SELECT Id, Etichetta_IT__c, Domanda_IT__c, Questionario__c, Raggruppamento__c, Albero__c, Tipologia__c, Obbligatoria__c,
                Suggerimento__c, Data_Ora_Inizio__c, Data_Ora_Fine__c, Visibile__c, Considerare__c, Ordine__c, Insieme_Opzioni_Domanda__c,
                (SELECT Id, Utente__c, Valore_Numerico__c FROM Risposte_questionario__r), Raggruppamento__r.Gruppo__r.Name, Raggruppamento__r.Gruppo__r.Colore__c, Raggruppamento__r.Etichetta_IT__c
                FROM Domanda_Questionario__c 
                WHERE Raggruppamento__r.Gruppo__c IN :groupsIds
                AND Data_Ora_Inizio__c <= :currentDatetime AND Data_Ora_Fine__c >= :currentDatetime
                AND Raggruppamento__r.Azienda_Permessi_Visualizzazione__c IN :userPermissions
                ORDER BY Priorita__c ASC, Data_Ora_Inizio__c ASC, Ordine__c ASC];
        
    }

}