Produzione/force-app/main/default/objects/Domanda_Questionario__c/Domanda_Questionario__c.object-meta.xml
<CustomObject>
    <description>Domande che compongono il questionario</description>
    <label>Domanda Questionario</label>
    <nameField>
        <label>Nome Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domande Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine della domanda all&apos;interno della pagina/sezione</description>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Domanda_Questionario__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia della domanda</description>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Informativo</fullName>
            </value>
            <value>
                <fullName>Testo semplice</fullName>
            </value>
            <value>
                <fullName>Testo lungo</fullName>
            </value>
            <value>
                <fullName>Numerico	Numerico</fullName>
            </value>
            <value>
                <fullName>Valutazione</fullName>
            </value>
            <value>
                <fullName>Vero/falso</fullName>
            </value>
            <value>
                <fullName>Scelta multipla</fullName>
            </value>
            <value>
                <fullName>Valutazione multipla</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Menu di selezione singol</fullName>
            </value>
            <value>
                <fullName>Opzione</fullName>
            </value>
            <value>
                <fullName>Radio con commento</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio</fullName>
            </value>
            <value>
                <fullName>Radio con commento obbligatorio se minore di 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gruppo__c/fields/Colore__c.field-meta.xml
<CustomField>
    <fullName>Colore__c</fullName>
    <description>Colore associato al gruppo</description>
    <inlineHelpText>Colore associato al gruppo</inlineHelpText>
    <label>Colore</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Genitore__c.field-meta.xml
<CustomField>
    <fullName>Genitore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Genitore</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Gruppi</relationshipLabel>
    <relationshipName>Gruppi</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Gruppo__c/fields/Gruppo_Master__c.field-meta.xml
<CustomField>
    <fullName>Gruppo_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gruppo principale al quale è collegato. Necessario solo se l&apos;alberatura dipende da un&apos;alberatura principale. Come nel caso di TFS che dipenderà direttamente dall&apos;alberatura di TMI</description>
    <inlineHelpText>Gruppo principale al quale è collegato. Necessario solo se l&apos;alberatura dipende da un&apos;alberatura principale. Come nel caso di TFS che dipenderà direttamente dall&apos;alberatura di TMI</inlineHelpText>
    <label>Gruppo Master</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Gruppi (Gruppo Master)</relationshipLabel>
    <relationshipName>Gruppi_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</description>
    <inlineHelpText>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</inlineHelpText>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <description>Sigla zona / distretto</description>
    <inlineHelpText>Sigla zona / distretto</inlineHelpText>
    <label>Sigla</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/force-app/main/default/objects/Gruppo__c/fields/URL_Logo__c.field-meta.xml
<CustomField>
    <fullName>URL_Logo__c</fullName>
    <description>Logo gruppo</description>
    <label>URL_Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Raggruppamento__c/Raggruppamento__c.object-meta.xml
<CustomObject>
    <label>Raggruppamento</label>
    <nameField>
        <label>Nome Raggruppamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raggruppamenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Raggruppamento__c/fields/Azienda_Permessi_Visualizzazione__c.field-meta.xml
<CustomField>
    <fullName>Azienda_Permessi_Visualizzazione__c</fullName>
    <description>Specifica a quale azienda appartiene il raggruppamento, di modo che in base all&apos;utente possano essere filtrati</description>
    <inlineHelpText>Specifica a quale azienda appartiene il raggruppamento, di modo che in base all&apos;utente possano essere filtrati</inlineHelpText>
    <label>Azienda Permessi Visualizzazione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Aziende_Permessi_Visualizzazione</valueSetName>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Raggruppamento__c/fields/Genitore__c.field-meta.xml
<CustomField>
    <fullName>Genitore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raggruppamento</label>
    <referenceTo>Raggruppamento__c</referenceTo>
    <relationshipLabel>Raggruppamenti</relationshipLabel>
    <relationshipName>Raggruppamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Raggruppamento__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gruppo</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Raggruppamenti</relationshipLabel>
    <relationshipName>Raggruppamenti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raggruppamento__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indice</fullName>
            </value>
            <value>
                <fullName>Raggruppamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/Risposta_Questionario__c.object-meta.xml
<CustomObject>
    <description>Risposte del questionario</description>
    <label>Risposta Questionario</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Nome Risposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risposte Questionario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Domanda_Questionario__c.field-meta.xml
<CustomField>
    <fullName>Domanda_Questionario__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Domanda a cui ha risposto</description>
    <label>Domanda Questionario</label>
    <referenceTo>Domanda_Questionario__c</referenceTo>
    <relationshipLabel>Risposte Questionario</relationshipLabel>
    <relationshipName>Risposte_Questionario</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Risposta_questionario__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utente Custom</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Risposte questionario</relationshipLabel>
    <relationshipName>Risposte_questionario</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Valore_Numerico__c</fullName>
    <description>Eventuale risposta numerica</description>
    <label>Valore Numerico</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Testuale__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale__c</fullName>
    <description>Eventuale risposta testuale</description>
    <label>Valore Testuale</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Risposta_Questionario__c/fields/Valore_Testuale_Lungo__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale_Lungo__c</fullName>
    <description>Eventuale risposta testuale lunga</description>
    <label>Valore Testuale Lungo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente__c/fields/Azienda_Permessi_Visualizzazione__c.field-meta.xml
<CustomField>
    <fullName>Azienda_Permessi_Visualizzazione__c</fullName>
    <description>Definisce quali raggruppamenti l&apos;utente manager può visualizzare</description>
    <inlineHelpText>Definisce quali raggruppamenti l&apos;utente manager può visualizzare</inlineHelpText>
    <label>Azienda Permessi Visualizzazione</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Aziende_Permessi_Visualizzazione</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Non_Considerare_Analisi__c.field-meta.xml
<CustomField>
    <fullName>Non_Considerare_Analisi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Per considerare o meno opinione utente nelle analisi</description>
    <inlineHelpText>Per considerare o meno opinione utente nelle analisi</inlineHelpText>
    <label>Non Considerare Analisi</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Utente_Master__c.field-meta.xml
<CustomField>
    <fullName>Utente_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</description>
    <inlineHelpText>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</inlineHelpText>
    <label>Utente Master</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Master</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente_Gruppo__c/Utente_Gruppo__c.object-meta.xml
<CustomObject>
    <label>Utente Gruppo</label>
    <nameField>
        <label>Nome Utente Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente_Gruppo__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gruppo</label>
    <referenceTo>Gruppo__c</referenceTo>
    <relationshipLabel>Utenti Gruppi</relationshipLabel>
    <relationshipName>Utenti_Gruppi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente_Gruppo__c/fields/Gruppo_Master__c.field-meta.xml
<CustomField>
    <fullName>Gruppo_Master__c</fullName>
    <description>Gruppo Master di riferimento</description>
    <formula>Gruppo__r.Gruppo_Master__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gruppo Master</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente_Gruppo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utente Custom</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Gruppi</relationshipLabel>
    <relationshipName>Utenti_Gruppi</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/ManagerSuggestionsResource.cls
@RestResource(urlMapping='/manager_suggestions/*')
global class ManagerSuggestionsResource {
    
    @HttpGet
    global static void doGet(){
        
        CustomAuthentication ca = new CustomAuthentication(RestContext.request, RestContext.response);
        
        if(!ca.authenticate()){
            
            ca.getResponse().send();
            
            return;
            
        }
        
        CustomResponse res = new CustomResponse(RestContext.response);
        
        Utente__c u = ca.getUser();
        Id userId = u.Utente_Master__c != null ? u.Utente_Master__c : u.Id;
        List<String> userPermissions = u.Azienda_Permessi_Visualizzazione__c != null ? u.Azienda_Permessi_Visualizzazione__c.split(';') : new List<String>();
        
        String brandId = RestContext.request.params.get('brandId');
        String zonesIds = RestContext.request.params.get('zonesIds');
        String sentimentsString = RestContext.request.params.get('sentiments');
        
        /*Gruppo__c g = [SELECT Id, Gruppo_Master__c FROM Gruppo__c WHERE Id = :brandId LIMIT 1];
        
        if(g.Gruppo_Master__c != null){
            brandId = g.Gruppo_Master__c;
        }*/
        
        Gruppo__c brand = [SELECT Id, Genitore__c, Name, Tipologia__c, Sigla__c, Ordine__c, Url_Logo__c, Colore__c, Gruppo_Master__c
                           FROM Gruppo__c WHERE Id = :brandId];
        
        List<Object> suggestions = new List<Object>();
        
        //List<Gruppo__c> allGroups = UserResource.getAllGroups();
        //List<Gruppo__c> userGroups = UserResource.getUserGroups(u.Id);
        List<Gruppo__c> childGroups = UserResource.getUserGroupChildren(u.Id);
        childGroups = UserResource.filterGroupsByBrandId(childGroups, brandId);
        
        if(String.isNotBlank(zonesIds)){
            
            childGroups = UserResource.getGroupsByIds(zonesIds.split(','));
            
        }
        
        List<String> sentiments = String.isNotBlank(sentimentsString) ? sentimentsString.split(',') : new List<String>();
        List<Integer> sentimentsInt = new List<Integer>();
        
        for(String s: sentiments){
            sentimentsInt.add(Integer.valueOf(s));
        }
        
        suggestions.addAll(getSuggestions(brand, childGroups, sentimentsInt, userPermissions));
        
        res.setStatusCode(200);
        res.setBody(suggestions);
        
        res.send();
        
    }
    
    public static List<Object> getSuggestions(Gruppo__c brand, List<Gruppo__c> childGroups, List<Integer> sentiments, List<String> userPermissions){
                
        Set<Id> childGroupsIds = new Set<Id>();
        
        for(Gruppo__c cg : childGroups){
            childGroupsIds.add(cg.Id);
        }
        
        List<Utente_Gruppo__c> usersGroups = [SELECT Id, Utente__c, Gruppo__r.Name, Name FROM Utente_Gruppo__c 
                                              WHERE Gruppo__r.Genitore__r.Genitore__c = :brand.Id 
                                              AND Utente__r.Non_Considerare_Analisi__c = false AND Utente__r.Tipologia__c = 'Dealer'
                                              AND Gruppo__c IN :childGroupsIds];
        
        Set<Id> usersToAnalyze = new Set<Id>();
        
        for(Utente_Gruppo__c ug : usersGroups){
            
            usersToAnalyze.add(ug.Utente__c);
            
        }
        
        Set<Integer> values = new Set<Integer>();
        
        if(sentiments.size() <= 0){
            values.add(1);
            values.add(2);
            values.add(3);
            values.add(4);
            values.add(5);
        }
        
        if(sentiments.contains(-1)){
            values.add(1);
            values.add(2);
        }
        
        if(sentiments.contains(0)){
            values.add(3);
        }
        
        if(sentiments.contains(1)){
            values.add(4);
            values.add(5);
        }
        
        List<Risposta_questionario__c> answers = [SELECT Name, Utente__c, Valore_Numerico__c, Valore_Testuale__c, Valore_Testuale_Lungo__c, Domanda_questionario__r.Raggruppamento__c,
                                                  Domanda_questionario__r.Raggruppamento__r.Genitore__c, Domanda_questionario__r.Raggruppamento__r.Gruppo__r.Name,
                                                  Domanda_questionario__r.Raggruppamento__r.Peso_Genitore__c, Domanda_questionario__r.Data_Ora_Inizio__c,
                                                  Valore_Numerico_Per_Peso_Raggruppamento__c, Domanda_questionario__r.Data_Ora_Fine__c, Utente__r.Non_Considerare_Analisi__c,
                                                  Domanda_questionario__r.Data_Ora_Inizio_Analisi__c, Domanda_questionario__r.Data_Ora_Fine_Analisi__c, Data_Ora_Risposta__c,
                                                  Utente__r.Ragione_Sociale__c, Domanda_questionario__r.Raggruppamento__r.Gruppo__c, Domanda_questionario__r.Raggruppamento__r.Name,
                                                  Domanda_questionario__r.Domanda_IT__c, Domanda_questionario__r.Raggruppamento__r.Etichetta_IT__c,
                                                  Domanda_questionario__r.Raggruppamento__r.Gruppo__r.Genitore__c, Domanda_questionario__r.Raggruppamento__r.Gruppo__r.Tipologia__c,
                                                  Utente__r.Name, Utente__r.Nome__c, Utente__r.Cognome__c, Domanda_questionario__r.Raggruppamento__r.Gruppo__r.Colore__c
                                                  FROM Risposta_questionario__c
                                                  WHERE Utente__c = :usersToAnalyze AND Valore_Numerico__c = :values
                                                  AND (Valore_Numerico__c != null OR Valore_Testuale__c != null)
                                                  AND Data_Ora_Risposta__c >= :System.now().addMonths(-6) AND Data_Ora_Risposta__c <= :System.now()
                                                  AND (Domanda_questionario__r.Raggruppamento__r.Gruppo__r.Tipologia__c = 'Casa Auto'
                                                       OR Domanda_questionario__r.Raggruppamento__r.Gruppo__c = :brand.Id
                                                       OR Domanda_questionario__r.Raggruppamento__r.Gruppo__c = :brand.Gruppo_Master__c)
                                                  AND Domanda_questionario__r.Raggruppamento__r.Azienda_Permessi_Visualizzazione__c IN :userPermissions
                                                  ORDER BY Domanda_questionario__r.Data_Ora_Inizio__c DESC, Data_Ora_Risposta__c DESC];
        
        List<SuggestionGrouping> suggestionGrouping = new List<SuggestionGrouping>();

        for(Risposta_questionario__c a : answers){
            
            if(String.isNotBlank(a.Valore_Testuale_Lungo__c) && a.Valore_Testuale_Lungo__c.length() > 3){
            
                SuggestionGrouping sg;
                
                for(SuggestionGrouping s : suggestionGrouping){
                    if(s.id == a.Domanda_questionario__r.Raggruppamento__c){
                        sg = s;
                    }
                }
                
                if(sg == null){
                    
                    sg = new SuggestionGrouping(a.Domanda_questionario__r.Raggruppamento__c, a.Domanda_questionario__r.Raggruppamento__r.Etichetta_IT__c);
                    sg.color = a.Domanda_questionario__r.Raggruppamento__r.Gruppo__r.Colore__c;
                    suggestionGrouping.add(sg);
                    
                }
                
                SuggestionQuestion sq;
                
                for(SuggestionQuestion s : sg.questions){
                    if(s.id == a.Domanda_questionario__c){
                        sq = s;
                    }
                }
                
                if(sq == null){
                    
                    Long questionStartDateTime = a.Domanda_questionario__r.Data_Ora_Inizio__c != null ? a.Domanda_questionario__r.Data_Ora_Inizio__c.getTime() : null;
                    Long questionEndDateTime = a.Domanda_questionario__r.Data_Ora_Fine__c != null ? a.Domanda_questionario__r.Data_Ora_Fine__c.getTime() : null;
                    
                    sq = new SuggestionQuestion(a.Domanda_questionario__c, a.Domanda_questionario__r.Domanda_IT__c, questionStartDateTime, questionEndDateTime);
                    sg.questions.add(sq);
                    
                }
                
                SuggestionAnswer sa = new SuggestionAnswer(a.Id, a.Valore_Testuale_Lungo__c, a.Valore_Numerico__c, a.Data_Ora_Risposta__c.getTime());
                
                for(Utente_Gruppo__c ug : usersGroups){
            
                    if(ug.Utente__c == a.Utente__c){
                        
                        sa.label = '<strong>' + a.Utente__r.Nome__c + ' ' + a.Utente__r.Cognome__c + '</strong> - [' + ug.Gruppo__r.Name + ']<br/>' + sa.label;
                        
                    }
                    
                }
                
                sq.answers.add(sa);
                sg.positive += sa.value > 3 ? 1 : 0;
                sg.negative += sa.value < 3 ? 1 : 0;
                sg.neutral += sa.value == 3 ? 1 : 0;
                
            }
        }
        
        String info = 'Le <b>suggestion</b> sono indicazioni fornite dai Concessionari, espresse rilasciando un <b>commento ai quesiti</b> sottoposti.<br/><br/>';
        info += 'Per ciascun ambito si riportano in evidenza il numero di commenti <b>positivi</b> (verde), <b>neutrali</b> (giallo) o <b>negativi</b> (rosso) rilasciati nei periodi di rilevazione considerati.<br/><br/>';
        info += 'L\'ordine delle tematiche e dei commenti seguono la logica del più recente.<br/><br/>';
        info += 'Gli ambiti identificati con color coding \'grigio\' rappresentano aree comuni ai marchi Toyota e Lexus, per le quali è stato rilevato un unico quesito non diversificato per marchio.';
        
        for(SuggestionGrouping sg : suggestionGrouping){
            sg.info = info;
        }
        
        return suggestionGrouping;
        
    }
    
    class SuggestionGrouping{
        
        public String id;
        public String label;
        public String info;
        public String color;
        public Integer positive = 0;
        public Integer negative = 0;
        public Integer neutral = 0;
        public List<SuggestionQuestion> questions = new List<SuggestionQuestion>();
        
        SuggestionGrouping(String id, String label){
			this.id = id;
			this.label = label;       
        }
        
    }
    
    class SuggestionQuestion{
        
        public String id;
        public String label;
        public Long startTimestamp;
        public Long endTimestamp;
        public List<SuggestionAnswer> answers = new List<SuggestionAnswer>();
        
        SuggestionQuestion(String id, String label, Long startTimestamp, Long endTimestamp){
			this.id = id;
			this.label = label;     
			this.startTimestamp = startTimestamp;
			this.endTimestamp = endTimestamp;
        }
        
    }
    
    class SuggestionAnswer{
        
        public String id;
        public String label;
        public Decimal value;
        public Long timestamp;
        
        SuggestionAnswer(String id, String label, Decimal value, Long timestamp){
			this.id = id;
			this.label = label;
			this.value = value;
			this.timestamp = timestamp;            
        }
        
    }

}