Produzione/force-app/main/default/objects/Accesso__c/Accesso__c.object-meta.xml
<CustomObject>
    <description>Accessi utente</description>
    <label>Accesso</label>
    <nameField>
        <displayFormat>ACC-{00000000}</displayFormat>
        <label>Nome Accessi</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accessi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Accesso__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato all&apos;accesso</description>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Accessi</relationshipLabel>
    <relationshipName>Accessi</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Produzione/force-app/main/default/classes/AccessTokenResource.cls
@RestResource(urlMapping='/access_token/*')
global class AccessTokenResource {
    
    @HttpPost
    global static void getToken(String nickname, String password){
        
        CustomAuthentication ca = new CustomAuthentication(RestContext.request, RestContext.response);
        
        ca.authenticateWithNicknameAndPassword(nickname, password);
        
        if(ca != null && ca.getUser() != null && !ca.isStealth()){
        
            insert new Accesso__c(Utente__c = ca.getUser().Id);
            
        }
		
        ca.getResponse().send();
        
    }
    
}