Produzione/force-app/main/default/objects/Accesso__c/Accesso__c.object-meta.xml
<CustomObject>
    <description>Accessi utente</description>
    <label>Accesso</label>
    <nameField>
        <displayFormat>ACC-{00000000}</displayFormat>
        <label>Nome Accessi</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accessi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Accesso__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia di accesso</description>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login</fullName>
                <default>true</default>
                <label>Login</label>
            </value>
            <value>
                <fullName>Brit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Accesso__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato all&apos;accesso</description>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Accessi</relationshipLabel>
    <relationshipName>Accessi</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Aree_KPI__c/BRiT_Aree_KPI__c.object-meta.xml
<CustomObject>
    <label>BRiT Area KPI</label>
    <nameField>
        <label>Cod_Area_KPI</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRiT Aree KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BRiT_KPI__c/BRiT_KPI__c.object-meta.xml
<CustomObject>
    <label>BRiT KPI</label>
    <nameField>
        <label>Cod_KPI</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRiT KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/BRiT_KPI__c/fields/Cod_Area_KPI__c.field-meta.xml
<CustomField>
    <fullName>Cod_Area_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cod_Area_KPI</label>
    <referenceTo>BRiT_Aree_KPI__c</referenceTo>
    <relationshipLabel>Cod_Area_KPI</relationshipLabel>
    <relationshipName>Cod_Area_KPI</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_KPI__c/fields/CondizioneMaggioreDi__c.field-meta.xml
<CustomField>
    <fullName>CondizioneMaggioreDi__c</fullName>
    <description>Se impostato un valore la colorazione del numero visualizzato in app diventerà rossa se prima e verde se dopo, nero se non presente.</description>
    <inlineHelpText>Se impostato un valore la colorazione del numero visualizzato in app diventerà rossa se prima e verde se dopo, nero se non presente.</inlineHelpText>
    <label>CondizioneMaggioreDi</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_KPI__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <label>KPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRiT_KPI__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <label>Ordine</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Risultati__c/BRiT_Risultati__c.object-meta.xml
<CustomObject>
    <label>BRiT Risultato</label>
    <nameField>
        <label>Nome BRiT Risultato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRiT Risultati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/BRiT_Risultati__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRiT_Risultati__c/fields/Benchmark__c.field-meta.xml
<CustomField>
    <fullName>Benchmark__c</fullName>
    <label>Benchmark</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BRiT_Risultati__c/fields/Cod_Casa__c.field-meta.xml
<CustomField>
    <fullName>Cod_Casa__c</fullName>
    <label>Cod_Casa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRiT_Risultati__c/fields/Cod_KPI__c.field-meta.xml
<CustomField>
    <fullName>Cod_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cod_KPI</label>
    <referenceTo>BRiT_KPI__c</referenceTo>
    <relationshipLabel>Cod_KPI</relationshipLabel>
    <relationshipName>Cod_KPI_Risultati</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Risultati__c/fields/Distretto__c.field-meta.xml
<CustomField>
    <fullName>Distretto__c</fullName>
    <label>Distretto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Risultati__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <label>Gruppo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRiT_Risultati__c/fields/Marchio__c.field-meta.xml
<CustomField>
    <fullName>Marchio__c</fullName>
    <label>Marchio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Risultati__c/fields/Nome_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Nome_Dealer__c</fullName>
    <label>Nome Dealer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Risultati__c/fields/Non_visualizzare__c.field-meta.xml
<CustomField>
    <fullName>Non_visualizzare__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non visualizzare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BRiT_Risultati__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Risultati__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Visualizzazioni__c/BRiT_Visualizzazioni__c.object-meta.xml
<CustomObject>
    <label>BRiT Visualizzazione</label>
    <nameField>
        <label>BRiT Visualizzazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRiT Visualizzazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/BRiT_Visualizzazioni__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BRiT_Visualizzazioni__c/fields/Cod_KPI__c.field-meta.xml
<CustomField>
    <fullName>Cod_KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cod_KPI</label>
    <referenceTo>BRiT_KPI__c</referenceTo>
    <relationshipLabel>BRiT Visualizzazioni</relationshipLabel>
    <relationshipName>Cod_KPI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BRiT_Visualizzazioni__c/fields/Mese__c.field-meta.xml
<CustomField>
    <fullName>Mese__c</fullName>
    <label>Mese</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gruppo__c/fields/Colore__c.field-meta.xml
<CustomField>
    <fullName>Colore__c</fullName>
    <description>Colore associato al gruppo</description>
    <inlineHelpText>Colore associato al gruppo</inlineHelpText>
    <label>Colore</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/fields/Ordine__c.field-meta.xml
<CustomField>
    <fullName>Ordine__c</fullName>
    <description>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</description>
    <inlineHelpText>Ordine di visualizzazione del gruppo, generalmente utilizzato per i quesiti</inlineHelpText>
    <label>Ordine</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente__c/fields/COD_CASA__c.field-meta.xml
<CustomField>
    <fullName>COD_CASA__c</fullName>
    <description>Codice della casa auto</description>
    <inlineHelpText>Codice della casa auto</inlineHelpText>
    <label>COD CASA</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/classes/BritResultResource.cls
@RestResource(urlMapping='/britresult/*')
global class BritResultResource {
    
    @HttpGet
    global static void doGet(){
        
        String device = RestContext.request.headers.get('x-device-id');
        system.debug(device);
        
        CustomAuthentication ca = new CustomAuthentication(RestContext.request, RestContext.response);
        
        if(!ca.authenticate()){
            
            ca.getResponse().send();
        
            return;
            
        }
        
        if(ca != null && ca.getUser() != null && !ca.isStealth()) {
			insert new Accesso__c(Utente__c = ca.getUser().Id, Tipologia__c = 'Brit');
		}
        
        CustomResponse res = new CustomResponse(RestContext.response);
        
        Utente__c u = ca.getUser();
        List<String> codici = u.COD_CASA__c.split(',');

        // recupero i KPI da visualizzare
        List<BRiT_Visualizzazioni__c> visualizzati = [SELECT Cod_KPI__c, Mese__c, Anno__c, Marchio__c FROM BRiT_Visualizzazioni__c];
        system.debug(visualizzati);
        
        Map<String, String> daVisualizzare = new Map<String,String>();
        for(BRiT_Visualizzazioni__c visualizzato : visualizzati){
            String chiaveVis = visualizzato.Anno__c + visualizzato.Mese__c + visualizzato.Marchio__c + visualizzato.Cod_KPI__c;
            daVisualizzare.put(chiaveVis,chiaveVis);
        }
        
        // struttura di appoggio Map<keyConcatenato, BritResult> --> keyConcatenato = brit1.Anno__c+brit1.Mese__c+brit1.Cod_Casa__c+brit1.Marchio__c
        // struttura di appoggio Map<keyArea, String> --> keyConcatenato+keyArea
        // sttuttura di appoggio Map<keyBrit, String> --> keyConcatenato+keyArea+keyBrit
        
        // for BRiT_Risultati__c
        // 	controllo se esiste un valore per Map<keyConcatenato>
        // 		se esiste prendo il BritResult dalla map
        // 		se non esiste creo un nuovo Map<keyConcatenato, BritResult>
        // 		hai il BritResult
        // 			controllo se nella mappa BritAreaKpi di questo BritResult c'è già la chiave corrente Map<keyArea>
        // 				se si prendo Map<keyArea>
        // 				ma se no creo nuovo campo Map<keyArea, new BritAreaKpi ...
        // 					controllo se nella mappa BritKpi esiste già un Map<keyBrit>
        // 						se si prendo Map<keyBrit>
        // 						se no creo Map<keyBrit, new BritKpi
        
        List<BRiT_Risultati__c> brits = [SELECT id, Anno__c, Benchmark__c, Cod_Casa__c, Cod_KPI__c, Cod_KPI__r.id, Cod_KPI__r.Name, Cod_KPI__r.Ordine__c, Cod_KPI__r.KPI__c,
                                         Cod_KPI__r.Cod_Area_KPI__c, Cod_KPI__r.CondizioneMaggioreDi__c, Cod_KPI__r.Cod_Area_KPI__r.Color__c, Cod_KPI__r.Cod_Area_KPI__r.Ordine__c, Cod_KPI__r.Cod_Area_KPI__r.Area_KPI__c,
                                         Distretto__c, Gruppo__c, Marchio__c, Mese__c, Nome_Dealer__c, Non_visualizzare__c, 
                                         Value__c, Zona__c FROM BRiT_Risultati__c WHERE Cod_Casa__c in :codici AND Non_visualizzare__c = false
                                         ORDER BY /*Cod_Casa__c DESC, */Marchio__c DESC, Anno__c DESC, Mese__c DESC, Cod_KPI__r.Cod_Area_KPI__r.Ordine__c ASC, Cod_KPI__r.Ordine__c ASC];
        
        // recupero i colori
        Set<String> marchi = new Set<String>();
        Set<String> gruppi = new Set<String>();
        for(BRiT_Risultati__c marchio : brits){
            marchi.add(marchio.Marchio__c);
            gruppi.add(marchio.Gruppo__c);
        }
        List<Gruppo__c> colors = [SELECT Name, Colore__c FROM Gruppo__c WHERE Name IN :marchi AND Tipologia__c = 'Marchio' ];
        Map<String, String> marchioColore = new Map<String, String>();
        for(Gruppo__c color : colors){
            if(!marchioColore.containsKey(color.Name))
            	marchioColore.put(color.Name, color.Colore__c);
        }
        
        
        Map<String, BritResult> britresults = new Map<String, BritResult>();
        Map<String, String> areas = new Map<String, String>();
        Map<String, String> kpis = new Map<String, String>();
        
        for(BRiT_Risultati__c brit : brits){
            
            String chiavebrit = brit.Anno__c + brit.Mese__c + brit.Cod_Casa__c + brit.Marchio__c;
            String chiavearea = brit.Anno__c + brit.Mese__c + brit.Cod_Casa__c + brit.Marchio__c + brit.Cod_KPI__r.Cod_Area_KPI__c;
            String chiavekpi = brit.Anno__c + brit.Mese__c + brit.Cod_Casa__c + brit.Marchio__c + brit.Cod_KPI__r.Cod_Area_KPI__c + brit.Cod_KPI__c;
            String chiaveDaVisualizzare = brit.Anno__c + brit.Mese__c + brit.Marchio__c + brit.Cod_KPI__c;
            
            if(daVisualizzare.get(chiaveDaVisualizzare) != null) {
                // le kpi sono sempre nuove
                BritKpi kpi = new BritKpi(brit.Cod_KPI__r.KPI__c, brit.Cod_KPI__r.CondizioneMaggioreDi__c, brit.Value__c, brit.Benchmark__c);
                kpis.put(chiavekpi, brit.Cod_KPI__r.KPI__c);       
                
                if(areas.get(chiavearea) == null){
                    // non ho ancora creato l'area, quindi la creo
                    List<BritKpi> kpiList = new List<BritKpi>();
                    kpiList.add(kpi);
                    BritAreaKpi areakpi = new BritAreaKpi(brit.Cod_KPI__r.Cod_Area_KPI__r.Area_KPI__c, brit.Cod_KPI__r.Cod_Area_KPI__r.Color__c, kpiList);
                    
                    // controllo se il britresult esiste già
                    if(britresults.get(chiavebrit) == null){
                        //creo il nuovo britresult e ci butto sentro l'area
                        BritResult br = new BritResult(brit.id, brit.Anno__c, brit.Cod_Casa__c, brit.Distretto__c, brit.Marchio__c, brit.Mese__c, brit.Zona__c, brit.Gruppo__c, brit.Nome_Dealer__c, marchioColore, new List<BritAreaKpi>());
                        br.results.add(areakpi);
                        areas.put(chiavearea, brit.Cod_KPI__r.Cod_Area_KPI__c); 
                        britresults.put(chiavebrit, br);
                        
                    } else {
                        // aggiungo l'area a un britresult esistente
                        BritResult br = britresults.get(chiavebrit);
                        br.results.add(areakpi);
                        areas.put(chiavearea, brit.Cod_KPI__r.Cod_Area_KPI__c); 
                    }
                    
                } else {
                    // l'area esiste già, devo trovare quella giusta e andare a inserirci il nuovo kpi
                    BritResult britResultEsistente = britresults.get(chiavebrit);
                    List<BritAreaKpi> britAreaList = britResultEsistente.results;
                    for(BritAreaKpi bak : britAreaList){
                        if(bak.getArea() == brit.Cod_KPI__r.Cod_Area_KPI__r.Area_KPI__c){
                            bak.kpis.add(kpi);    
                        }
                    }    
                }
            }
        }
        

        // costruisco la lista dei risultati
        List<BritResult> returnList = new List<BritResult>();
        for (String key : britresults.keySet()) {
            returnList.add(britresults.get(key));
        }
        


        res.setStatusCode(200);
        res.setBody(returnList);
        
        res.send();
        
    }

}