Produzione/force-app/main/default/objects/App__c/App__c.object-meta.xml
<CustomObject>
    <description>App alla quale un utente custom sarà collegato</description>
    <label>App</label>
    <nameField>
        <label>Nome App</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Azienda__c.field-meta.xml
<CustomField>
    <fullName>Azienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Azienda</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Utente__c/fields/CAP__c.field-meta.xml
<CustomField>
    <fullName>CAP__c</fullName>
    <description>CAP</description>
    <label>CAP</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Citta__c.field-meta.xml
<CustomField>
    <fullName>Citta__c</fullName>
    <description>Città di riferimento dealer</description>
    <inlineHelpText>Città di riferimento dealer</inlineHelpText>
    <label>Città</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/CL_Anzianita__c.field-meta.xml
<CustomField>
    <fullName>CL_Anzianita__c</fullName>
    <description>Classe di anzienità</description>
    <inlineHelpText>Classe di anzienità</inlineHelpText>
    <label>CL Anzianità</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/CL_Fatturato__c.field-meta.xml
<CustomField>
    <fullName>CL_Fatturato__c</fullName>
    <description>Classe di fatturato</description>
    <inlineHelpText>Classe di fatturato</inlineHelpText>
    <label>CL Fatturato</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/CL_Vendite__c.field-meta.xml
<CustomField>
    <fullName>CL_Vendite__c</fullName>
    <description>Classe di vendite</description>
    <inlineHelpText>Classe di vendite</inlineHelpText>
    <label>CL Vendite</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/COD_CASA__c.field-meta.xml
<CustomField>
    <fullName>COD_CASA__c</fullName>
    <description>Codice della casa auto</description>
    <inlineHelpText>Codice della casa auto</inlineHelpText>
    <label>COD CASA</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Cognome__c.field-meta.xml
<CustomField>
    <fullName>Cognome__c</fullName>
    <description>Cognome dell&apos;utente</description>
    <inlineHelpText>Cognome dell&apos;utente</inlineHelpText>
    <label>Cognome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Data_Ora_Accettazione_Privacy__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Accettazione_Privacy__c</fullName>
    <label>Data Ora Accettazione Privacy</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Dismesso__c.field-meta.xml
<CustomField>
    <fullName>Dismesso__c</fullName>
    <description>Se settata una data non può più accedere alla app</description>
    <inlineHelpText>Se settata una data non può più accedere alla app</inlineHelpText>
    <label>Dismesso</label>
    <type>Date</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Indirizzo_Sede_Legale__c.field-meta.xml
<CustomField>
    <fullName>Indirizzo_Sede_Legale__c</fullName>
    <description>Indirizzo completo della sede legale</description>
    <inlineHelpText>Indirizzo completo della sede legale</inlineHelpText>
    <label>Indirizzo Sede Legale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome dell&apos;utente</description>
    <inlineHelpText>Nome dell&apos;utente</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Nome_Commerciale__c.field-meta.xml
<CustomField>
    <fullName>Nome_Commerciale__c</fullName>
    <description>Nome commerciale per visualizzazione nelle liste dei dealer</description>
    <inlineHelpText>Nome commerciale per visualizzazione nelle liste dei dealer</inlineHelpText>
    <label>Nome Commerciale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Non_Considerare_Analisi__c.field-meta.xml
<CustomField>
    <fullName>Non_Considerare_Analisi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Per considerare o meno opinione utente nelle analisi</description>
    <inlineHelpText>Per considerare o meno opinione utente nelle analisi</inlineHelpText>
    <label>Non Considerare Analisi</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/PIVA__c.field-meta.xml
<CustomField>
    <fullName>PIVA__c</fullName>
    <description>Partita IVA aziendale</description>
    <inlineHelpText>Partita IVA aziendale</inlineHelpText>
    <label>PIVA</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <description>Provincia di riferimento</description>
    <inlineHelpText>Provincia di riferimento</inlineHelpText>
    <label>Provincia</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Ragione_Sociale__c.field-meta.xml
<CustomField>
    <fullName>Ragione_Sociale__c</fullName>
    <description>Ragione sociale dell&apos;azienda collegata</description>
    <inlineHelpText>Ragione sociale dell&apos;azienda collegata</inlineHelpText>
    <label>Ragione Sociale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Referente__c.field-meta.xml
<CustomField>
    <fullName>Referente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Riferimento_Immagine_Profilo__c.field-meta.xml
<CustomField>
    <fullName>Riferimento_Immagine_Profilo__c</fullName>
    <description>Riferimento firebase all&apos;immagine</description>
    <label>Riferimento Immagine Profilo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Ruolo__c.field-meta.xml
<CustomField>
    <fullName>Ruolo__c</fullName>
    <description>Ruolo del contatto</description>
    <label>Ruolo</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente__c/fields/URL_Foto__c.field-meta.xml
<CustomField>
    <fullName>URL_Foto__c</fullName>
    <description>Url per la foto del profilo utente</description>
    <inlineHelpText>Url per la foto del profilo utente</inlineHelpText>
    <label>URL Foto</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Utente_Master__c.field-meta.xml
<CustomField>
    <fullName>Utente_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</description>
    <inlineHelpText>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</inlineHelpText>
    <label>Utente Master</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Master</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Chat__c/Utente_Chat__c.object-meta.xml
<CustomObject>
    <description>Relazione tra l&apos;utente e la chat utilizzata nel working group</description>
    <label>Utente Chat</label>
    <nameField>
        <displayFormat>UCH-{0000000}</displayFormat>
        <label>Nome Utente Chat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utenti Chat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente_Chat__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Utente di riferimento</description>
    <inlineHelpText>Utente di riferimento</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Chat</relationshipLabel>
    <relationshipName>Utenti_Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/UserData.cls
public class UserData {
    
    public String id;
    public String appId;
    public String accountId;
    public String zipCode;
    public String city;
    public String seniority;
    public String revenue;
    public String sales;
    public String manufacturerCode;
    public String lastName;
    public Long decommissioned;
    public String email;
    public String legalAddress;
    public String nickname;
    public String firstName;
    public String commercialName;
    public Boolean notConsiderInAnalysis;
    public String vatNumber;
    public String province;
    public String companyName;
    public String contactId;
    public String district;
    public String companyRole;
    public String role;
    public String profilePictureUrl;
    public String profilePicturePath;
    public Long privacyAcceptedAt;
    public List<String> brands = new List<String>();
    public List<String> groups = new List<String>();
    public Boolean slave = false;
    public List<GroupData> parentGroups;
    public List<GroupData> childGroups;
    
    public String deviceId;
    public String token;
    
    public Integer answeredQuestions;
    public Integer viewedArticles;
    public Integer receivedNotifications;
    
    public UserData(){}
    
    DateTime toDateTime(Date d){
        
        return DateTime.newInstance(d, Time.newInstance(0, 0, 0, 0));
        
    }
    
    public void fromUtente(Utente__c user){
        
        Long decommissioned;
        
        if(user.Dismesso__c != null){
            
            decommissioned = toDateTime(user.Dismesso__c).getTime();
            
        }
        
        this.id = user.Id;
        this.accountId = user.Azienda__c;
        //this.answeredQuestions = null;
        this.appId = user.App__c;
        //this.brands = null;
        //this.childGroups = null;
        this.city = user.Citta__c;
        this.commercialName = user.Nome_Commerciale__c;
        this.companyName = user.Ragione_Sociale__c;
        this.companyRole = user.Ruolo__c;
        this.contactId = user.Referente__c;
        this.decommissioned = decommissioned;
        //this.deviceId = null;
        //this.district = null;
        this.email = user.Email__c;
        this.firstName = user.Nome__c;
        this.lastName = user.Cognome__c;
        this.legalAddress = user.Indirizzo_Sede_Legale__c;
        this.manufacturerCode = user.COD_CASA__c;
        this.nickname = user.Nickname__c;
        this.notConsiderInAnalysis = user.Non_Considerare_Analisi__c;
        //this.parentGroups = null;
        this.privacyAcceptedAt = user.Data_Ora_Accettazione_Privacy__c != null ? user.Data_Ora_Accettazione_Privacy__c.getTime() : null;
        this.profilePictureUrl = user.URL_Foto__c;
        this.profilePicturePath = user.Riferimento_Immagine_Profilo__c;
        this.province = user.Provincia__c;
        //this.receivedNotifications = null;
        this.revenue = user.CL_Fatturato__c;
        this.role = user.Tipologia__c;
        this.sales = user.CL_Vendite__c;
        this.seniority = user.CL_Anzianita__c;
        this.slave = user.Utente_Master__c != null;
        //this.token = null;
        this.vatNumber = user.PIVA__c;
        //this.viewedArticles = null;
        this.zipCode = user.CAP__c;
        
    }
    
    public void fromUtenteChat(Utente_Chat__c userChat){
        
        Long decommissioned;
        
        if(userChat.Utente__r.Dismesso__c != null){
            
            decommissioned = toDateTime(userChat.Utente__r.Dismesso__c).getTime();
            
        }
        
        this.id = userChat.Utente__r.Id;
        this.accountId = userChat.Utente__r.Azienda__c;
        this.appId = userChat.Utente__r.App__c;
        this.city = userChat.Utente__r.Citta__c;
        this.commercialName = userChat.Utente__r.Nome_Commerciale__c;
        this.companyName = userChat.Utente__r.Ragione_Sociale__c;
        this.companyRole = userChat.Utente__r.Ruolo__c;
        this.contactId = userChat.Utente__r.Referente__c;
        this.decommissioned = decommissioned;
        this.email = userChat.Utente__r.Email__c;
        this.firstName = userChat.Utente__r.Nome__c;
        this.lastName = userChat.Utente__r.Cognome__c;
        this.legalAddress = userChat.Utente__r.Indirizzo_Sede_Legale__c;
        this.manufacturerCode = userChat.Utente__r.COD_CASA__c;
        this.nickname = userChat.Utente__r.Nickname__c;
        this.notConsiderInAnalysis = userChat.Utente__r.Non_Considerare_Analisi__c;
        this.privacyAcceptedAt = userChat.Utente__r.Data_Ora_Accettazione_Privacy__c != null ? userChat.Utente__r.Data_Ora_Accettazione_Privacy__c.getTime() : null;
        this.profilePictureUrl = userChat.Utente__r.URL_Foto__c;
        this.profilePicturePath = userChat.Utente__r.Riferimento_Immagine_Profilo__c;
        this.province = userChat.Utente__r.Provincia__c;
        this.revenue = userChat.Utente__r.CL_Fatturato__c;
        this.role = userChat.Utente__r.Tipologia__c;
        this.sales = userChat.Utente__r.CL_Vendite__c;
        this.seniority = userChat.Utente__r.CL_Anzianita__c;
        this.slave = userChat.Utente__r.Utente_Master__c != null;
        this.vatNumber = userChat.Utente__r.PIVA__c;
        this.zipCode = userChat.Utente__r.CAP__c;
        
    }
    
}