Produzione/force-app/main/default/objects/App__c/App__c.object-meta.xml
<CustomObject>
    <description>App alla quale un utente custom sarà collegato</description>
    <label>App</label>
    <nameField>
        <label>Nome App</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configurazione_App__c/Configurazione_App__c.object-meta.xml
<CustomObject>
    <description>Oggetto di configurazione dell&apos;app</description>
    <label>Configurazione App</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Nome Configurazione App</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurazioni App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configurazione_App__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Configurazioni App</relationshipLabel>
    <relationshipName>Configurazioni_App</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Booleano__c.field-meta.xml
<CustomField>
    <fullName>Campo_Booleano__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Campo Booleano</label>
    <type>Checkbox</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Data__c.field-meta.xml
<CustomField>
    <fullName>Campo_Data__c</fullName>
    <label>Campo Data</label>
    <type>Date</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Data_Ora__c.field-meta.xml
<CustomField>
    <fullName>Campo_Data_Ora__c</fullName>
    <label>Campo Data Ora</label>
    <type>DateTime</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Campo_Numerico__c</fullName>
    <label>Campo Numerico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Campo_Testuale__c.field-meta.xml
<CustomField>
    <fullName>Campo_Testuale__c</fullName>
    <label>Campo Testuale</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Chiave__c.field-meta.xml
<CustomField>
    <fullName>Chiave__c</fullName>
    <label>Chiave</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/Configurazione_App__c/fields/Sezione__c.field-meta.xml
<CustomField>
    <fullName>Sezione__c</fullName>
    <label>Sezione</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generale</fullName>
            </value>
            <value>
                <fullName>Dealer Map</fullName>
            </value>
            <value>
                <fullName>Dealer Insight</fullName>
            </value>
            <value>
                <fullName>Dealer More Results</fullName>
            </value>
            <value>
                <fullName>Grafici</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Configurazione_App__c/fields/Tipologia_Campo__c.field-meta.xml
<CustomField>
    <fullName>Tipologia_Campo__c</fullName>
    <label>Tipologia Campo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Numerico</fullName>
            </value>
            <value>
                <fullName>Testuale</fullName>
            </value>
            <value>
                <fullName>Booleano</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Data Ora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/classes/AppInfoResourceTest.cls
@isTest
public class AppInfoResourceTest {
    
    static String endpoint = '/services/apexrest/app_info';
    
    @testSetup
    static void setup(){
        
        App__c app = new App__c();
        
        insert app;
        
        List<Configurazione_App__c> appConfigs = new List<Configurazione_App__c>();
        Configurazione_App__c appConfig = new Configurazione_App__c();
        
        appConfig.App__c = app.Id;
        appConfig.Chiave__c = 'chiave_testuale';
        appConfig.Sezione__c = 'Grafici';
        appConfig.Tipologia_Campo__c = 'Testuale';
        appConfig.Campo_Testuale__c = 'testo';
        
        appConfigs.add(appConfig);
        
        appConfig = new Configurazione_App__c();
        
        appConfig.App__c = app.Id;
        appConfig.Chiave__c = 'chiave_booleana';
        appConfig.Sezione__c = 'Grafici';
        appConfig.Tipologia_Campo__c = 'Booleano';
        appConfig.Campo_Booleano__c = true;
        
        appConfigs.add(appConfig);
        
        appConfig = new Configurazione_App__c();
        
        appConfig.App__c = app.Id;
        appConfig.Chiave__c = 'chiave_numerica';
        appConfig.Sezione__c = 'Grafici';
        appConfig.Tipologia_Campo__c = 'Numerico';
        appConfig.Campo_Numerico__c = 12;
        
        appConfigs.add(appConfig);
        
        appConfig = new Configurazione_App__c();
        
        appConfig.App__c = app.Id;
        appConfig.Chiave__c = 'chiave_data';
        appConfig.Sezione__c = 'Grafici';
        appConfig.Tipologia_Campo__c = 'Data';
        appConfig.Campo_Data__c = System.today();
        
        appConfigs.add(appConfig);
        
        appConfig = new Configurazione_App__c();
        
        appConfig.App__c = app.Id;
        appConfig.Chiave__c = 'chiave_data_ora';
        appConfig.Sezione__c = 'Grafici';
        appConfig.Tipologia_Campo__c = 'Data Ora';
        appConfig.Campo_Data_Ora__c = System.now();
        
        appConfigs.add(appConfig);
        
        insert appConfigs;
        
    }
    
    static App__c getApp(){
        
        return [SELECT Id FROM App__c LIMIT 1];
        
    }
    
    @isTest
    static void testGetAppInfoResourceWithoutAppId(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        AppInfoResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode != 200);
        System.assert(body.containsIgnoreCase('error'));
        
    }
    
    @isTest
    static void testGetAppInfoResourceWithAppId(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = endpoint;
        req.httpMethod = 'GET';
        
        req.addHeader('x-app-id', getApp().Id);
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        
        AppInfoResource.doGet();
        
        Test.stopTest();
        
        String body = res.responseBody.toString();
        
        System.assert(res.statusCode == 200);
        System.assert(!body.containsIgnoreCase('error'));
        
    }

}