Produzione/force-app/main/default/objects/App__c/App__c.object-meta.xml
<CustomObject>
    <description>App alla quale un utente custom sarà collegato</description>
    <label>App</label>
    <nameField>
        <label>Nome App</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat utilizzata nei working group</description>
    <label>Chat</label>
    <nameField>
        <displayFormat>CH-{0000000}</displayFormat>
        <label>Nome Chat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>App di riferimento della chat</description>
    <inlineHelpText>App di riferimento della chat</inlineHelpText>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Chat</relationshipLabel>
    <relationshipName>Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Area di riferimento della chat</description>
    <inlineHelpText>Area di riferimento della chat</inlineHelpText>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>After Sales</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Development</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>TFM</fullName>
            </value>
            <value>
                <fullName>TFS</fullName>
            </value>
            <value>
                <fullName>TIM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Data_Ora_Chiusura__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Chiusura__c</fullName>
    <description>Data e ora della chiusura. Se impostata non sarà più possibile scrivere all&apos;interno della chat</description>
    <inlineHelpText>Data e ora della chiusura. Se impostata non sarà più possibile scrivere all&apos;interno della chat</inlineHelpText>
    <label>Data Ora Chiusura</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Data_Ora_Eliminazione__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Eliminazione__c</fullName>
    <description>Data e ora dell&apos;eliminazione della chat. Se impostata non è più possibile accedere alla chat</description>
    <inlineHelpText>Data e ora dell&apos;eliminazione della chat. Se impostata non è più possibile accedere alla chat</inlineHelpText>
    <label>Data Ora Eliminazione</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Descrizione__c.field-meta.xml
<CustomField>
    <fullName>Descrizione__c</fullName>
    <description>Descrizione della chat</description>
    <inlineHelpText>Descrizione della chat</inlineHelpText>
    <label>Descrizione</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Chat__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome della chat (o nome del gruppo)</description>
    <inlineHelpText>Nome della chat (o nome del gruppo)</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/Chat__c/fields/Proprietario__c.field-meta.xml
<CustomField>
    <fullName>Proprietario__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Chi ha creato la chat</description>
    <inlineHelpText>Chi ha creato la chat</inlineHelpText>
    <label>Proprietario</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Chat</relationshipLabel>
    <relationshipName>Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Riferimento_Immagine__c.field-meta.xml
<CustomField>
    <fullName>Riferimento_Immagine__c</fullName>
    <description>Riferimento firebase all&apos;immagine</description>
    <label>Riferimento Immagine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <description>Tipologia della chat, se gruppo o tra 2 persone</description>
    <inlineHelpText>Tipologia della chat, se gruppo o tra 2 persone</inlineHelpText>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>channel</fullName>
                <label>Canale</label>
            </value>
            <value>
                <fullName>direct</fullName>
                <default>true</default>
                <label>Doppia</label>
            </value>
            <value>
                <fullName>group</fullName>
                <label>Gruppo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat__c/fields/URL_Immagine__c.field-meta.xml
<CustomField>
    <fullName>URL_Immagine__c</fullName>
    <description>URL dell&apos;immagine della chat</description>
    <inlineHelpText>URL dell&apos;immagine della chat</inlineHelpText>
    <label>URL Immagine</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/Dispositivo__c/Dispositivo__c.object-meta.xml
<CustomObject>
    <description>Dispositivi collegati all&apos;utente per generazione token di sessione</description>
    <label>Dispositivo</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Nome Dispositivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispositivi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Dispositivo__c/fields/Firebase_Token__c.field-meta.xml
<CustomField>
    <fullName>Firebase_Token__c</fullName>
    <label>Firebase Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dispositivo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato</description>
    <inlineHelpText>Utente collegato a questo dispositivo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Dispositivi</relationshipLabel>
    <relationshipName>Dispositivi</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utente__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <referenceTo>App__c</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Azienda__c.field-meta.xml
<CustomField>
    <fullName>Azienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Azienda</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Utenti Custom</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Cognome__c.field-meta.xml
<CustomField>
    <fullName>Cognome__c</fullName>
    <description>Cognome dell&apos;utente</description>
    <inlineHelpText>Cognome dell&apos;utente</inlineHelpText>
    <label>Cognome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome dell&apos;utente</description>
    <inlineHelpText>Nome dell&apos;utente</inlineHelpText>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Ragione_Sociale__c.field-meta.xml
<CustomField>
    <fullName>Ragione_Sociale__c</fullName>
    <description>Ragione sociale dell&apos;azienda collegata</description>
    <inlineHelpText>Ragione sociale dell&apos;azienda collegata</inlineHelpText>
    <label>Ragione Sociale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Riferimento_Immagine_Profilo__c.field-meta.xml
<CustomField>
    <fullName>Riferimento_Immagine_Profilo__c</fullName>
    <description>Riferimento firebase all&apos;immagine</description>
    <label>Riferimento Immagine Profilo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Utente__c/fields/Ruolo__c.field-meta.xml
<CustomField>
    <fullName>Ruolo__c</fullName>
    <description>Ruolo del contatto</description>
    <label>Ruolo</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente__c/fields/URL_Foto__c.field-meta.xml
<CustomField>
    <fullName>URL_Foto__c</fullName>
    <description>Url per la foto del profilo utente</description>
    <inlineHelpText>Url per la foto del profilo utente</inlineHelpText>
    <label>URL Foto</label>
    <type>Url</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Chat__c/Utente_Chat__c.object-meta.xml
<CustomObject>
    <description>Relazione tra l&apos;utente e la chat utilizzata nel working group</description>
    <label>Utente Chat</label>
    <nameField>
        <displayFormat>UCH-{0000000}</displayFormat>
        <label>Nome Utente Chat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utenti Chat</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente_Chat__c/fields/Abilita_Storico__c.field-meta.xml
<CustomField>
    <fullName>Abilita_Storico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Abilita la visualizzazione dello storico dei messaggi</description>
    <inlineHelpText>Abilita la visualizzazione dello storico dei messaggi</inlineHelpText>
    <label>Abilita Storico</label>
    <type>Checkbox</type>
</CustomField>

Sandbox/force-app/main/default/objects/Utente_Chat__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Chat di riferimento</description>
    <inlineHelpText>Chat di riferimento</inlineHelpText>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Utenti Chat</relationshipLabel>
    <relationshipName>Utenti_Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Sandbox/force-app/main/default/objects/Utente_Chat__c/fields/Data_Ora_Aggiunta__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Aggiunta__c</fullName>
    <description>Data e ora in cui è stato aggiunto l&apos;utente</description>
    <inlineHelpText>Data e ora in cui è stato aggiunto l&apos;utente</inlineHelpText>
    <label>Data Ora Aggiunta</label>
    <type>DateTime</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente_Chat__c/fields/Data_Ora_Rimozione__c.field-meta.xml
<CustomField>
    <fullName>Data_Ora_Rimozione__c</fullName>
    <description>Data e ora di rimozione dell&apos;utente alla chat</description>
    <inlineHelpText>Data e ora di rimozione dell&apos;utente alla chat</inlineHelpText>
    <label>Data Ora Rimozione</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Utente_Chat__c/fields/Ruolo_Chat__c.field-meta.xml
<CustomField>
    <fullName>Ruolo_Chat__c</fullName>
    <description>Ruolo dell&apos;utente all&apos;interno della chat</description>
    <inlineHelpText>Ruolo dell&apos;utente all&apos;interno della chat</inlineHelpText>
    <label>Ruolo Chat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>admin</fullName>
                <label>Amministratore</label>
            </value>
            <value>
                <fullName>guest</fullName>
                <label>Ospite</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utente_Chat__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Utente di riferimento</description>
    <inlineHelpText>Utente di riferimento</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Chat</relationshipLabel>
    <relationshipName>Utenti_Chat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/UtenteChatUtils.cls
public class UtenteChatUtils {
    
    //private static String cloudFunctionsUrl = 'https://us-central1-tmi-rcc-dev.cloudfunctions.net';
    //private static String secretKey = 'FC87870580712462C0577DDA12D77B041B81DE5F58200EBFCE86C0B835057C02';    
    
    public static void insertFromTrigger(Map<Id, Utente_Chat__c> membersMap){
        
        Map<Id, Boolean> membersToAdd = new Map<Id, Boolean>();
        
        for(Id memberId : membersMap.keySet()){
            membersToAdd.put(memberId, true);
        }
        
        addOrRemoveMembers(membersMap, membersToAdd);
        
    }
    
    public static void updateFromTrigger(Map<Id, Utente_Chat__c> newUsersChatsMap, Map<Id, Utente_Chat__c> oldUsersChatsMap){
        
        Map<Id, Utente_Chat__c> membersToAddOrRemoveList = new Map<Id, Utente_Chat__c>();
        Map<Id, Boolean> membersToAddOrRemove = new Map<Id, Boolean>();
        
        for(String key : newUsersChatsMap.keySet()){
            
            Utente_Chat__c newUsersChats = newUsersChatsMap.get(key);
            Utente_Chat__c oldUsersChats = oldUsersChatsMap.get(key);
            
            if(newUsersChats.Data_Ora_Rimozione__c != null && oldUsersChats.Data_Ora_Rimozione__c == null){
                
                membersToAddOrRemoveList.put(newUsersChats.Id, newUsersChats);
                membersToAddOrRemove.put(newUsersChats.Id, false);
                
            }
            
            if(newUsersChats.Data_Ora_Rimozione__c == null && oldUsersChats.Data_Ora_Rimozione__c != null){
                
                membersToAddOrRemoveList.put(newUsersChats.Id, newUsersChats);
                membersToAddOrRemove.put(newUsersChats.Id, true);
                
            }
            
            
        }
        
        if(membersToAddOrRemoveList.size() > 0){
            
            addOrRemoveMembers(membersToAddOrRemoveList, membersToAddOrRemove);
                
        }
        
    }
    
    private static void addOrRemoveMembers(Map<Id, Utente_Chat__c> membersMap, Map<Id, Boolean> userToAddOrRemove){
        
        Set<Id> userIds = new Set<Id>();
        Set<Id> chatIds = new Set<Id>();
        
        for(String key : membersMap.keySet()){
            userIds.add(membersMap.get(key).Utente__c);
            chatIds.add(membersMap.get(key).Chat__c);
        }
        
        Map<Id, Utente__c> userMap = getUserMapByIds(userIds);        
        Map<Id, Chat__c> chatMap = getChatMapByIds(chatIds);        
        
        List<Object> messages = new List<Object>();        
        
        List<Utente_Chat__c> members = [SELECT Id, Chat__c, Ruolo_Chat__c, Utente__r.Azienda__c, Utente__r.Nome__c, Utente__r.Cognome__c, Utente__r.Tipologia__c, 
                                        Utente__r.Riferimento_Immagine_Profilo__c, Utente__c, Data_Ora_Aggiunta__c, Data_Ora_Rimozione__c, Abilita_Storico__c
                                        FROM Utente_Chat__c WHERE Chat__c IN :chatIds];
        
        for(String key : membersMap.keySet()){
            
            Utente_Chat__c member = membersMap.get(key);
            
            Utente__c currentUser;
            Chat__c currentChat;
            
            if(userMap.containsKey(member.Utente__c)){
                
                currentUser = userMap.get(member.Utente__c);
                
            }
            
            if(chatMap.containsKey(member.Chat__c)){
                
                currentChat = chatMap.get(member.Chat__c);
                
            }
            
            QCloudFunctions.QFirebaseMessage data = new QCloudFunctions.QFirebaseMessage();
            
            data.setUserFields(currentUser);
            data.setChatFields(currentChat);
            data.setUserChatFields(member);
            
            List<Utente_Chat__c> chatMembers = new List<Utente_Chat__c>();
            
            for(Utente_Chat__c chatMember : members){
                
                if(chatMember.Chat__c == member.Chat__c){
                    
                    chatMembers.add(chatMember);
                    
                }                
                
            }
            
        	data.setChatMembersFields(chatMembers);            
            
            data.message_type = userToAddOrRemove.get(key) ? 'add_to_chat' : 'remove_from_chat';
            
            messages.add(data);
        }
        
        QCloudFunctions.doRequest('/addMessages', 'POST', JSON.serialize(new Map<String, Object>{'messages' => messages}, false), null);
        
        sendMailLog(JSON.serialize(new Map<String, Object>{'messages' => messages}));
        
    }
    
    private static Map<Id, Utente__c> getUserMapByIds(Set<Id> usersIds){
        Map<Id, Utente__c> out = new Map<Id, Utente__c>();
        List<Utente__c> users = [SELECT Id, Nome__c, Cognome__c, Ragione_Sociale__c, Tipologia__c, Ruolo__c, URL_Foto__c, Riferimento_Immagine_Profilo__c,
                                 (SELECT Id, Firebase_Token__c, Utente__c FROM Dispositivi__r) 
                                 FROM Utente__c 
                                 WHERE Id IN :usersIds];
        
        for(Utente__c u : users){
            
            out.put(u.Id, u);
            
        }
        
        return out;
    }
    
    private static Map<Id, Chat__c> getChatMapByIds(Set<Id> chatsIds){
        Map<Id, Chat__c> out = new Map<Id, Chat__c>();
        List<Chat__c> chats = [SELECT Id, App__c, Area__c, Data_Ora_Chiusura__c, Data_Ora_Eliminazione__c, Descrizione__c, Nome__c, Proprietario__c, Tipologia__c, URL_Immagine__c,
                               Riferimento_Immagine__c, LastModifiedDate 
                               FROM Chat__c WHERE Id IN :chatsIds];
        
        for(Chat__c c : chats){
            
            out.put(c.Id, c);
            
        }
        return out;
    }
    
    @future
    private static void sendMailLog(String body){
        
        Map<String, Object> mailConf = new Map<String, Object>();
        
        mailConf.put('senderName', 'Francesco');
        mailConf.put('subject', 'Log - UtenteChatUtils');
        mailConf.put('htmlBody', body);
        mailConf.put('textBody', body);
        mailConf.put('attachment', null);
        mailConf.put('recipients', new List<String>{'francesco.marchesin@quintegia.it'});
        
        QUtilities.sendMail(mailConf);
        
    }
    
}