Sandbox/force-app/main/default/objects/Opzione_Domanda__c/Opzione_Domanda__c.object-meta.xml
<CustomObject>
    <label>Opzione Domanda</label>
    <nameField>
        <label>Nome Opzione Domanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opzioni Domande</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/force-app/main/default/objects/Opzione_Domanda__c/fields/Etichetta_Risultati_IT__c.field-meta.xml
<CustomField>
    <fullName>Etichetta_Risultati_IT__c</fullName>
    <label>Etichetta Risultati IT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Opzione_Domanda_IT__c.field-meta.xml
<CustomField>
    <fullName>Opzione_Domanda_IT__c</fullName>
    <label>Opzione Domanda IT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Opzione_Domanda__c/fields/Valore_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Valore_Numerico__c</fullName>
    <label>Valore Numerico</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opzione_Domanda__c/fields/Valore_Testuale__c.field-meta.xml
<CustomField>
    <fullName>Valore_Testuale__c</fullName>
    <label>Valore Testuale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/classes/QuestionOptionData.cls
public class QuestionOptionData {
    
    public String id;
    public String label;
    public String questionOption;
    public Decimal numericValue;
    public String textValue;
    
    public QuestionOptionData(Opzione_Domanda__c questionOption){
        
        this.id = questionOption.Id;
        this.label = questionOption.Etichetta_Risultati_IT__c;
        this.questionOption = questionOption.Opzione_Domanda_IT__c;
        this.numericValue = questionOption.Valore_Numerico__c;
        this.textValue = questionOption.Valore_Testuale__c;
        
    }
    
}