force-app/main/default/objects/BRiT_KPI__c/BRiT_KPI__c.object-meta.xml
<CustomObject>
    <label>BRiT KPI</label>
    <nameField>
        <label>Cod_KPI</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRiT KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/BRiT_KPI__c/fields/CondizioneMaggioreDi__c.field-meta.xml
<CustomField>
    <fullName>CondizioneMaggioreDi__c</fullName>
    <description>Se impostato un valore la colorazione del numero visualizzato in app diventerà rossa se prima e verde se dopo, nero se non presente.</description>
    <inlineHelpText>Se impostato un valore la colorazione del numero visualizzato in app diventerà rossa se prima e verde se dopo, nero se non presente.</inlineHelpText>
    <label>CondizioneMaggioreDi</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_KPI__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <label>KPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/classes/BritKpi.cls
public class BritKpi {

    String kpi;
    String value;
    String benchmark;
    Decimal CondizioneMaggioreDi;

    /*public BritKpi(BRiT_KPI__c kpi, Decimal valueKpi, Decimal benchmarkKpi){
        
        this.kpi = kpi.KPI__c;
        this.value = (valueKpi != null) ? String.valueOf(valueKpi) : null;
        this.benchmark = (benchmarkKpi != null) ? String.valueOf(benchmarkKpi) : null;
        this.CondizioneMaggioreDi = (kpi.CondizioneMaggioreDi__c != null) ? kpi.CondizioneMaggioreDi__c : null;
        
    }*/
    
    public BritKpi(String kpi, Decimal condizione,  Decimal valueKpi, Decimal benchmarkKpi){
        
        this.kpi = kpi;
        this.value = (valueKpi != null) ? String.valueOf(valueKpi) : null;
        this.benchmark = (benchmarkKpi != null) ? String.valueOf(benchmarkKpi) : null;
        this.CondizioneMaggioreDi = condizione;
        
    }
    
}