Produzione/force-app/main/default/objects/BRiT_Aree_KPI__c/BRiT_Aree_KPI__c.object-meta.xml
<CustomObject>
    <label>BRiT Area KPI</label>
    <nameField>
        <label>Cod_Area_KPI</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRiT Aree KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/BRiT_Aree_KPI__c/fields/Area_KPI__c.field-meta.xml
<CustomField>
    <fullName>Area_KPI__c</fullName>
    <label>Area_KPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/BRiT_Aree_KPI__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/classes/BritAreaKpi.cls
public class BritAreaKpi {

    String area;
  	String color;
  	public List<BritKpi> kpis = new List<BritKpi>();

    /*public BritAreaKpi(BRiT_Aree_KPI__c areaKpi, List<BritKpi> kpi){
        
        this.area = areaKpi.Area_KPI__c;
        this.color = String.isNotBlank(areaKpi.Color__c) ? areaKpi.Color__c: '';
        this.kpis = kpi;
    }*/
    public BritAreaKpi(String area, String color, List<BritKpi> kpi){
        
        this.area = area;
        this.color = color;
        this.kpis = kpi;
    }
    
    public String getArea(){
        return area;
    }
}