Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Utente_Master__c.field-meta.xml
<CustomField>
    <fullName>Utente_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</description>
    <inlineHelpText>Se impostato l&apos;utente corrente agirà (in lettura) come se fosse l&apos;utente master</inlineHelpText>
    <label>Utente Master</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Utenti Master</relationshipLabel>
    <relationshipName>Utenti_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

Produzione/force-app/main/default/classes/NotificationResource.cls
@RestResource(urlMapping='/notifications/*')
global class NotificationResource {
    
    @HttpGet
    global static void doGet(){
        
        CustomAuthentication ca = new CustomAuthentication(RestContext.request, RestContext.response);
        
        if(!ca.authenticate()){
            
            ca.getResponse().send();
        
            return;
            
        }
        
        CustomResponse res = new CustomResponse(RestContext.response);
        
        Utente__c user = ca.getUser();
        
        List<NotificationData> notifications = new List<NotificationData>();
        
        Integer questionCount = QuestionResource.getUserQuestionsCountByUserId(user.Id, null);
        Integer contentsCount = ArticleResource.countAllUserArticles(user.Id);
        Integer contentsCovid19Count = ArticleResource.countAllUserCovid19Articles(user.Id);
        Integer countAllUserDocumentsArticles = ArticleResource.countAllUserDocumentsArticles(user.Id);
        
        if(user.Tipologia__c == 'Dealer' && user.Utente_Master__c == null){
        
        	notifications.add(new NotificationData('questions_screen', questionCount));
            
        }
        
        notifications.add(new NotificationData('articles_screen', contentsCount));
        notifications.add(new NotificationData('covid_19_screen', contentsCovid19Count));
        //notifications.add(new NotificationData('documents_screen', countAllUserDocumentsArticles));
        
        res.setBody(notifications);
        
        res.send();
        
    }

}