Produzione/force-app/main/default/objects/BRIT__c/BRIT__c.object-meta.xml
<CustomObject>
    <label>BRIT</label>
    <nameField>
        <displayFormat>BRIT-{000000}</displayFormat>
        <label>Nome BRIT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BRITs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/BRIT__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <description>Anno a 4 cifre</description>
    <inlineHelpText>Anno a 4 cifre</inlineHelpText>
    <label>Anno</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/Codice__c.field-meta.xml
<CustomField>
    <fullName>Codice__c</fullName>
    <description>Codice</description>
    <label>Codice</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/CUSTOMER_CENTRICITY_Connected_Car__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CENTRICITY_Connected_Car__c</fullName>
    <description>CUSTOMER CENTRICITY - Connected Car</description>
    <label>CUSTOMER CENTRICITY - Connected Car</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/CUSTOMER_CENTRICITY_Customer_Retention__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CENTRICITY_Customer_Retention__c</fullName>
    <description>CUSTOMER CENTRICITY - Customer Retention</description>
    <label>CUSTOMER CENTRICITY - Customer Retention</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/Distretto__c.field-meta.xml
<CustomField>
    <fullName>Distretto__c</fullName>
    <description>Distretto</description>
    <label>Distretto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <description>Gruppo di appartenenza per Benchmark Rete</description>
    <inlineHelpText>Gruppo di appartenenza per Benchmark Rete</inlineHelpText>
    <label>Gruppo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>G1</fullName>
                <default>true</default>
                <label>G1</label>
            </value>
            <value>
                <fullName>G2</fullName>
            </value>
            <value>
                <fullName>G3</fullName>
            </value>
            <value>
                <fullName>G4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/Marchio__c.field-meta.xml
<CustomField>
    <fullName>Marchio__c</fullName>
    <description>Marchio</description>
    <label>Marchio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/Mese__c.field-meta.xml
<CustomField>
    <fullName>Mese__c</fullName>
    <description>Mese a 2 cifre</description>
    <inlineHelpText>Mese a 2 cifre</inlineHelpText>
    <label>Mese</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/Nome_dealer__c.field-meta.xml
<CustomField>
    <fullName>Nome_dealer__c</fullName>
    <description>Nome dealer</description>
    <label>Nome dealer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/PEOPLE_Digital_Customer_Advisor__c.field-meta.xml
<CustomField>
    <fullName>PEOPLE_Digital_Customer_Advisor__c</fullName>
    <description>PEOPLE - Digital Customer Advisor</description>
    <label>PEOPLE - Digital Customer Advisor</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/PEOPLE_Employee_Engagement_Survey__c.field-meta.xml
<CustomField>
    <fullName>PEOPLE_Employee_Engagement_Survey__c</fullName>
    <description>PEOPLE - Employee Engagement Survey</description>
    <label>PEOPLE - Employee Engagement Survey</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_AS_more_95__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_AS_more_95__c</fullName>
    <description>PRECOND. ACCESSO - Perf. A/S &gt; 95%</description>
    <label>PRECOND. ACCESSO - Perf. A/S &gt; 95%</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_NPS_more_75__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_NPS_more_75__c</fullName>
    <description>PRECOND. ACCESSO - Perf. NPS &gt; 75%</description>
    <label>PRECOND. ACCESSO - Perf. NPS &gt; 75%</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_Sales_more_95__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_Sales_more_95__c</fullName>
    <description>PRECOND. ACCESSO - Perf. Sales &gt; 95%</description>
    <label>PRECOND. ACCESSO - Perf. Sales &gt; 95%</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_Veicoli_Comm__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_Veicoli_Comm__c</fullName>
    <description>PRECONDIZIONI DI ACCESSO - Perf. Veicoli Commerciali</description>
    <label>PRECOND. ACCESSO - Perf. Veicoli Comm.</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - Penetrazione KINTO ONE</description>
    <label>SOST. DEL BUSINESS - Penetr. KINTO ONE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_Penetrazione_TCM__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_Penetrazione_TCM__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - Penetrazione TCM</description>
    <label>SOST. DEL BUSINESS - Penetrazione TCM</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_VCA__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_VCA__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - VCA</description>
    <label>SOST. DEL BUSINESS - VCA</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_We_Hybrid_Insurance__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_We_Hybrid_Insurance__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - We Hybrid Insurance</description>
    <label>SOST. DEL BUSINESS - We Hybrid Insurance</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/TOYOTA_WAY_Gestione_Lead__c.field-meta.xml
<CustomField>
    <fullName>TOYOTA_WAY_Gestione_Lead__c</fullName>
    <description>TOYOTA WAY - Gestione Lead</description>
    <label>TOYOTA WAY - Gestione Lead</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/TOYOTA_WAY_Qualita_dati_clienti__c.field-meta.xml
<CustomField>
    <fullName>TOYOTA_WAY_Qualita_dati_clienti__c</fullName>
    <description>TOYOTA WAY - Qualità dati clienti</description>
    <label>TOYOTA WAY - Qualità dati clienti</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <description>Zona</description>
    <label>Zona</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/classes/Brit.cls
public class Brit {
    
    public String id;
    public String year;
    public String code;
    public String customerCentricityConnectedCar;
    public String customerCentricityCustomerRetention;
    public String district;
    public String brand;
    public String month;
    public String dealerName;
    public String peopleDigitalCustomerAdvisor;
    public String peopleEmployeeEngagementSurvey;
    public String precondAccessoPerfAsMore95;
    public String precondAccessoPerfNpsMore75;
    public String precondAccessoPerfSalesMore95;
    public String precondAccessoPerfVeicoliComm;
    public String sostDelBusinessPenetrKintoOne;
    public String sostDelBusinessPenetrazioneTcm;
    public String sostDelBusinessVca;
    public String sostDelBusinessWeHybridInsurance;
    public String ToyotaWayGestioneLead;
    public String ToyotaWayQualitaDatiClienti;
    public String area;
    public String color;
    public String britGroup;
    public String info;
    
    public Brit(Brit__c brit, Map<String, String> colors){
        
        Map<String, String> meseAlpha = new Map<String, String>();
        meseAlpha.put('01', 'Gennaio');
        meseAlpha.put('02', 'Febbraio');
        meseAlpha.put('03', 'Marzo');
        meseAlpha.put('04', 'Aprile');
        meseAlpha.put('05', 'Maggio');
        meseAlpha.put('06', 'Giugno');
        meseAlpha.put('07', 'Luglio');
        meseAlpha.put('08', 'Agosto');
        meseAlpha.put('09', 'Settembre');
        meseAlpha.put('10', 'Ottobre');
        meseAlpha.put('11', 'Novembre');
        meseAlpha.put('12', 'Dicembre');
 
        this.id = brit.Id;
        this.year = String.isNotBlank(brit.Anno__c) ? brit.Anno__c : '';
        this.code = String.isNotBlank(brit.Codice__c) ? brit.Codice__c: '';
        this.customerCentricityConnectedCar = String.isNotBlank(String.valueOf(brit.CUSTOMER_CENTRICITY_Connected_Car__c)) ? String.valueOf(brit.CUSTOMER_CENTRICITY_Connected_Car__c) : '';
        this.customerCentricityCustomerRetention = String.isNotBlank(String.valueOf(brit.CUSTOMER_CENTRICITY_Customer_Retention__c)) ? String.valueOf(brit.CUSTOMER_CENTRICITY_Customer_Retention__c) : '';
        this.district = String.isNotBlank(brit.Distretto__c) ? brit.Distretto__c : '';
        this.brand = String.isNotBlank(brit.Marchio__c) ? brit.Marchio__c : '';
        this.month = String.isNotBlank(brit.Mese__c) ? meseAlpha.get(brit.Mese__c) : '';
        this.dealerName = String.isNotBlank(brit.Nome_dealer__c) ? brit.Nome_dealer__c : '';
        this.peopleDigitalCustomerAdvisor = String.isNotBlank(String.valueOf(brit.PEOPLE_Digital_Customer_Advisor__c)) ? String.valueOf(brit.PEOPLE_Digital_Customer_Advisor__c) : '';
        this.peopleEmployeeEngagementSurvey = String.isNotBlank(String.valueOf(brit.PEOPLE_Employee_Engagement_Survey__c)) ? String.valueOf(brit.PEOPLE_Employee_Engagement_Survey__c) : '';
        this.precondAccessoPerfAsMore95 = String.isNotBlank(String.valueOf(brit.PRECOND_ACCESSO_Perf_AS_more_95__c)) ? String.valueOf(brit.PRECOND_ACCESSO_Perf_AS_more_95__c) : '';
        this.precondAccessoPerfNpsMore75 = String.isNotBlank(String.valueOf(brit.PRECOND_ACCESSO_Perf_NPS_more_75__c)) ? String.valueOf(brit.PRECOND_ACCESSO_Perf_NPS_more_75__c) : '';
        this.precondAccessoPerfSalesMore95 = String.isNotBlank(String.valueOf(brit.PRECOND_ACCESSO_Perf_Sales_more_95__c)) ? String.valueOf(brit.PRECOND_ACCESSO_Perf_Sales_more_95__c) : '';
        this.precondAccessoPerfVeicoliComm = String.isNotBlank(String.valueOf(brit.PRECOND_ACCESSO_Perf_Veicoli_Comm__c)) ? String.valueOf(brit.PRECOND_ACCESSO_Perf_Veicoli_Comm__c) : '';
        this.sostDelBusinessPenetrKintoOne = String.isNotBlank(String.valueOf(brit.SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c)) ? String.valueOf(brit.SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c) : '';
        this.sostDelBusinessPenetrazioneTcm = String.isNotBlank(String.valueOf(brit.SOST_DEL_BUSINESS_Penetrazione_TCM__c)) ? String.valueOf(brit.SOST_DEL_BUSINESS_Penetrazione_TCM__c) : '';
        this.sostDelBusinessVca = String.isNotBlank(String.valueOf(brit.SOST_DEL_BUSINESS_VCA__c)) ? String.valueOf(brit.SOST_DEL_BUSINESS_VCA__c) : '';
        this.sostDelBusinessWeHybridInsurance = String.isNotBlank(String.valueOf(brit.SOST_DEL_BUSINESS_We_Hybrid_Insurance__c)) ? String.valueOf(brit.SOST_DEL_BUSINESS_We_Hybrid_Insurance__c) : '';
        this.ToyotaWayGestioneLead = String.isNotBlank(String.valueOf(brit.TOYOTA_WAY_Gestione_Lead__c)) ? String.valueOf(brit.TOYOTA_WAY_Gestione_Lead__c) : '';
        this.ToyotaWayQualitaDatiClienti = String.isNotBlank(String.valueOf(brit.TOYOTA_WAY_Qualita_dati_clienti__c)) ? String.valueOf(brit.TOYOTA_WAY_Qualita_dati_clienti__c) : '';
        this.area = String.isNotBlank(brit.Zona__c) ? brit.Zona__c : '';
        this.color = colors.containsKey(brit.Marchio__c) ? colors.get(brit.Marchio__c) : '';
        this.britGroup = String.isNotBlank(brit.Gruppo__c) ? brit.Gruppo__c : '';
		this.info = 'In questa sezione sono presentati i risultati di performance della sua concessionaria, per mese e marca, a confronto con la media del gruppo di riferimento in Rete (calcolato sulla base del potenziale di mercato).';

    }
    
}