Produzione/force-app/main/default/objects/BRIT__c/BRIT__c.object-meta.xml
<CustomObject>
    <label>BRIT</label>
    <nameField>
        <displayFormat>BRIT-{000000}</displayFormat>
        <label>Nome BRIT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BRITs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/BRIT__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <description>Anno a 4 cifre</description>
    <inlineHelpText>Anno a 4 cifre</inlineHelpText>
    <label>Anno</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/Codice__c.field-meta.xml
<CustomField>
    <fullName>Codice__c</fullName>
    <description>Codice</description>
    <label>Codice</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/CUSTOMER_CENTRICITY_Connected_Car__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CENTRICITY_Connected_Car__c</fullName>
    <description>CUSTOMER CENTRICITY - Connected Car</description>
    <label>CUSTOMER CENTRICITY - Connected Car</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/CUSTOMER_CENTRICITY_Customer_Retention__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CENTRICITY_Customer_Retention__c</fullName>
    <description>CUSTOMER CENTRICITY - Customer Retention</description>
    <label>CUSTOMER CENTRICITY - Customer Retention</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/Distretto__c.field-meta.xml
<CustomField>
    <fullName>Distretto__c</fullName>
    <description>Distretto</description>
    <label>Distretto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/Gruppo__c.field-meta.xml
<CustomField>
    <fullName>Gruppo__c</fullName>
    <description>Gruppo di appartenenza per Benchmark Rete</description>
    <inlineHelpText>Gruppo di appartenenza per Benchmark Rete</inlineHelpText>
    <label>Gruppo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>G1</fullName>
                <default>true</default>
                <label>G1</label>
            </value>
            <value>
                <fullName>G2</fullName>
            </value>
            <value>
                <fullName>G3</fullName>
            </value>
            <value>
                <fullName>G4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/Marchio__c.field-meta.xml
<CustomField>
    <fullName>Marchio__c</fullName>
    <description>Marchio</description>
    <label>Marchio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/Mese__c.field-meta.xml
<CustomField>
    <fullName>Mese__c</fullName>
    <description>Mese a 2 cifre</description>
    <inlineHelpText>Mese a 2 cifre</inlineHelpText>
    <label>Mese</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/Nome_dealer__c.field-meta.xml
<CustomField>
    <fullName>Nome_dealer__c</fullName>
    <description>Nome dealer</description>
    <label>Nome dealer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/PEOPLE_Digital_Customer_Advisor__c.field-meta.xml
<CustomField>
    <fullName>PEOPLE_Digital_Customer_Advisor__c</fullName>
    <description>PEOPLE - Digital Customer Advisor</description>
    <label>PEOPLE - Digital Customer Advisor</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/PEOPLE_Employee_Engagement_Survey__c.field-meta.xml
<CustomField>
    <fullName>PEOPLE_Employee_Engagement_Survey__c</fullName>
    <description>PEOPLE - Employee Engagement Survey</description>
    <label>PEOPLE - Employee Engagement Survey</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_AS_more_95__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_AS_more_95__c</fullName>
    <description>PRECOND. ACCESSO - Perf. A/S &gt; 95%</description>
    <label>PRECOND. ACCESSO - Perf. A/S &gt; 95%</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_NPS_more_75__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_NPS_more_75__c</fullName>
    <description>PRECOND. ACCESSO - Perf. NPS &gt; 75%</description>
    <label>PRECOND. ACCESSO - Perf. NPS &gt; 75%</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_Sales_more_95__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_Sales_more_95__c</fullName>
    <description>PRECOND. ACCESSO - Perf. Sales &gt; 95%</description>
    <label>PRECOND. ACCESSO - Perf. Sales &gt; 95%</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/PRECOND_ACCESSO_Perf_Veicoli_Comm__c.field-meta.xml
<CustomField>
    <fullName>PRECOND_ACCESSO_Perf_Veicoli_Comm__c</fullName>
    <description>PRECONDIZIONI DI ACCESSO - Perf. Veicoli Commerciali</description>
    <label>PRECOND. ACCESSO - Perf. Veicoli Comm.</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - Penetrazione KINTO ONE</description>
    <label>SOST. DEL BUSINESS - Penetr. KINTO ONE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_Penetrazione_TCM__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_Penetrazione_TCM__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - Penetrazione TCM</description>
    <label>SOST. DEL BUSINESS - Penetrazione TCM</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_VCA__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_VCA__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - VCA</description>
    <label>SOST. DEL BUSINESS - VCA</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BRIT__c/fields/SOST_DEL_BUSINESS_We_Hybrid_Insurance__c.field-meta.xml
<CustomField>
    <fullName>SOST_DEL_BUSINESS_We_Hybrid_Insurance__c</fullName>
    <description>SOSTENIBILITA&apos; DEL BUSINESS - We Hybrid Insurance</description>
    <label>SOST. DEL BUSINESS - We Hybrid Insurance</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/TOYOTA_WAY_Gestione_Lead__c.field-meta.xml
<CustomField>
    <fullName>TOYOTA_WAY_Gestione_Lead__c</fullName>
    <description>TOYOTA WAY - Gestione Lead</description>
    <label>TOYOTA WAY - Gestione Lead</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Produzione/force-app/main/default/objects/BRIT__c/fields/TOYOTA_WAY_Qualita_dati_clienti__c.field-meta.xml
<CustomField>
    <fullName>TOYOTA_WAY_Qualita_dati_clienti__c</fullName>
    <description>TOYOTA WAY - Qualità dati clienti</description>
    <label>TOYOTA WAY - Qualità dati clienti</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/force-app/main/default/objects/BRIT__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <description>Zona</description>
    <label>Zona</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Dispositivo__c/Dispositivo__c.object-meta.xml
<CustomObject>
    <description>Dispositivi collegati all&apos;utente per generazione token di sessione</description>
    <label>Dispositivo</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Nome Dispositivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispositivi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Dispositivo__c/fields/Dispositivo__c.field-meta.xml
<CustomField>
    <fullName>Dispositivo__c</fullName>
    <description>Identificativo del dispositivo</description>
    <inlineHelpText>Identificativo del dispositivo</inlineHelpText>
    <label>Dispositivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispositivo__c/fields/Utente__c.field-meta.xml
<CustomField>
    <fullName>Utente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utente collegato</description>
    <inlineHelpText>Utente collegato a questo dispositivo</inlineHelpText>
    <label>Utente</label>
    <referenceTo>Utente__c</referenceTo>
    <relationshipLabel>Dispositivi</relationshipLabel>
    <relationshipName>Dispositivi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gruppo__c/Gruppo__c.object-meta.xml
<CustomObject>
    <description>Gruppi di utenti custom</description>
    <label>Gruppo</label>
    <nameField>
        <label>Nome Gruppo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gruppi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gruppo__c/fields/Colore__c.field-meta.xml
<CustomField>
    <fullName>Colore__c</fullName>
    <description>Colore associato al gruppo</description>
    <inlineHelpText>Colore associato al gruppo</inlineHelpText>
    <label>Colore</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Produzione/force-app/main/default/objects/Gruppo__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Distretto</fullName>
            </value>
            <value>
                <fullName>Zona</fullName>
            </value>
            <value>
                <fullName>Casa Auto</fullName>
            </value>
            <value>
                <fullName>Marchio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/Utente__c.object-meta.xml
<CustomObject>
    <label>Utente Custom</label>
    <nameField>
        <label>Nome Utente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenti Custom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Produzione/force-app/main/default/objects/Utente__c/fields/COD_CASA__c.field-meta.xml
<CustomField>
    <fullName>COD_CASA__c</fullName>
    <description>Codice della casa auto</description>
    <inlineHelpText>Codice della casa auto</inlineHelpText>
    <label>COD CASA</label>
    <type>TextArea</type>
</CustomField>

Produzione/force-app/main/default/objects/Utente__c/fields/Tipologia__c.field-meta.xml
<CustomField>
    <fullName>Tipologia__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Produzione/force-app/main/default/classes/BritResource.cls
@RestResource(urlMapping='/brit/*')
global class BritResource {
    
    @HttpGet
    global static void doGet(){
        
        /*String yearMonth = RestContext.request.requestURI.substring(RestContext.request.requestURI.lastIndexOf('/')+1);
        String year = yearMonth.substring(0, 4);
        String month = yearMonth.substring(4, 6);*/
        
        String device = RestContext.request.headers.get('x-device-id');
        system.debug(device);
        
        CustomAuthentication ca = new CustomAuthentication(RestContext.request, RestContext.response);
        
        if(!ca.authenticate()){
            
            ca.getResponse().send();
        
            return;
            
        }
        
        CustomResponse res = new CustomResponse(RestContext.response);
        
        Dispositivo__c dis = [SELECT Utente__r.COD_CASA__c FROM Dispositivo__c WHERE Dispositivo__c = :device LIMIT 1];
        
        system.debug(dis.Utente__r.COD_CASA__c);
        
        List<String> codici = dis.Utente__r.COD_CASA__c.split(',');
        
        // recupero i brit dell'utente
        List<BRIT__c> brits = [SELECT id, Anno__c, Codice__c, CUSTOMER_CENTRICITY_Connected_Car__c, CUSTOMER_CENTRICITY_Customer_Retention__c, Distretto__c, Marchio__c, Mese__c, Nome_dealer__c, Gruppo__c,
                               PEOPLE_Digital_Customer_Advisor__c, PEOPLE_Employee_Engagement_Survey__c, PRECOND_ACCESSO_Perf_AS_more_95__c, PRECOND_ACCESSO_Perf_NPS_more_75__c, PRECOND_ACCESSO_Perf_Sales_more_95__c, 
                               PRECOND_ACCESSO_Perf_Veicoli_Comm__c, SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c, SOST_DEL_BUSINESS_Penetrazione_TCM__c, SOST_DEL_BUSINESS_VCA__c, SOST_DEL_BUSINESS_We_Hybrid_Insurance__c,
                               TOYOTA_WAY_Gestione_Lead__c, TOYOTA_WAY_Qualita_dati_clienti__c, Zona__c FROM BRIT__c WHERE /*Anno__c = :year AND Mese__c = :month AND*/ Codice__c in :codici
                               ORDER BY Anno__c DESC, Mese__c DESC, Marchio__c DESC];
        
        Set<String> marchi = new Set<String>();
        Set<String> gruppi = new Set<String>();
        for(BRIT__c marchio : brits){
            marchi.add(marchio.Marchio__c);
            gruppi.add(marchio.Gruppo__c);
        }
        
        List<BRIT__c> benchmarks = [SELECT id, Anno__c, Codice__c, CUSTOMER_CENTRICITY_Connected_Car__c, CUSTOMER_CENTRICITY_Customer_Retention__c, Distretto__c, Marchio__c, Mese__c, Nome_dealer__c, Gruppo__c,
                               PEOPLE_Digital_Customer_Advisor__c, PEOPLE_Employee_Engagement_Survey__c, PRECOND_ACCESSO_Perf_AS_more_95__c, PRECOND_ACCESSO_Perf_NPS_more_75__c, PRECOND_ACCESSO_Perf_Sales_more_95__c, 
                               PRECOND_ACCESSO_Perf_Veicoli_Comm__c, SOST_DEL_BUSINESS_Penetr_KINTO_ONE__c, SOST_DEL_BUSINESS_Penetrazione_TCM__c, SOST_DEL_BUSINESS_VCA__c, SOST_DEL_BUSINESS_We_Hybrid_Insurance__c,
                               TOYOTA_WAY_Gestione_Lead__c, TOYOTA_WAY_Qualita_dati_clienti__c, Zona__c FROM BRIT__c WHERE Codice__c = '' and Gruppo__c in :gruppi
                               ORDER BY Anno__c DESC, Mese__c DESC, Marchio__c DESC];
        
        List<Gruppo__c> colors = [SELECT Name, Colore__c FROM Gruppo__c WHERE Name IN :marchi AND Tipologia__c = 'Marchio' ];
        Map<String, String> marchioColore = new Map<String, String>();
        for(Gruppo__c color : colors){
            if(!marchioColore.containsKey(color.Name))
            	marchioColore.put(color.Name, color.Colore__c);
        }
        
        List<Brit> returnList = new List<Brit>();
        for(BRIT__c brit : brits){
            returnList.add(new Brit(brit, marchioColore));
        }
        
        for(BRIT__c benchmark : benchmarks){
            returnList.add(new Brit(benchmark, marchioColore));
        }

        res.setStatusCode(200);
        res.setBody(returnList);
        
        res.send();
        
    }

}